<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ActivityLogsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('activity_logs')->delete();
        
        \DB::table('activity_logs')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_id' => 1,
                'action' => 'payment_processed',
                'description' => 'Pagamento #3 processado para usuário Sofia Maria Chaúque',
                'metadata' => '"{\\"transaction_id\\":3,\\"amount\\":\\"50.00\\",\\"user_id\\":10,\\"method\\":\\"mpesa\\"}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-07 11:38:27',
                'updated_at' => '2026-02-07 11:38:27',
            ),
            1 => 
            array (
                'id' => 2,
                'user_id' => 1,
                'action' => 'payment_processed',
                'description' => 'Pagamento #4 processado para usuário Sofia Maria Chaúque',
                'metadata' => '"{\\"transaction_id\\":4,\\"amount\\":\\"70.00\\",\\"user_id\\":10,\\"method\\":\\"mpesa\\"}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-07 11:38:28',
                'updated_at' => '2026-02-07 11:38:28',
            ),
            2 => 
            array (
                'id' => 3,
                'user_id' => 1,
                'action' => 'payment_processed',
                'description' => 'Pagamento #6 processado para usuário Paulo José Matola',
                'metadata' => '"{\\"transaction_id\\":6,\\"amount\\":\\"50.00\\",\\"user_id\\":9,\\"method\\":\\"mpesa\\"}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-07 11:38:28',
                'updated_at' => '2026-02-07 11:38:28',
            ),
            3 => 
            array (
                'id' => 4,
                'user_id' => 1,
                'action' => 'user_created',
                'description' => 'Usuário Teste PowerShell criado pelo administrador',
                'metadata' => '"{\\"user_id\\":43,\\"role\\":\\"participant\\"}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-07 12:34:49',
                'updated_at' => '2026-02-07 12:34:49',
            ),
            4 => 
            array (
                'id' => 5,
                'user_id' => 1,
                'action' => 'user_updated',
                'description' => 'Usuário Teste PowerShell Atualizado atualizado pelo administrador',
            'metadata' => '"{\\"user_id\\":43,\\"changes\\":{\\"name\\":\\"Teste PowerShell Atualizado\\",\\"phone\\":\\"(84) 98888-8888\\",\\"status\\":\\"active\\"}}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-07 12:34:59',
                'updated_at' => '2026-02-07 12:34:59',
            ),
            5 => 
            array (
                'id' => 6,
                'user_id' => 1,
                'action' => 'user_updated',
                'description' => 'Usuário Teste PowerShell Atualizado atualizado pelo administrador',
                'metadata' => '"{\\"user_id\\":43,\\"changes\\":[]}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-07 12:55:34',
                'updated_at' => '2026-02-07 12:55:34',
            ),
            6 => 
            array (
                'id' => 7,
                'user_id' => 1,
                'action' => 'user_updated',
                'description' => 'Usuário Teste PowerShell Atualizado [MODIFICADO] atualizado pelo administrador',
                'metadata' => '"{\\"user_id\\":43,\\"changes\\":{\\"name\\":\\"Teste PowerShell Atualizado [MODIFICADO]\\",\\"phone\\":\\"844466353\\"}}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-07 15:15:24',
                'updated_at' => '2026-02-07 15:15:24',
            ),
            7 => 
            array (
                'id' => 8,
                'user_id' => 1,
                'action' => 'user_updated',
                'description' => 'Usuário Teste PowerShell Atualizado [MODIFICADO] atualizado pelo administrador',
                'metadata' => '"{\\"user_id\\":43,\\"changes\\":{\\"name\\":\\"Teste PowerShell Atualizado [MODIFICADO]\\",\\"email\\":\\"teste.powershell@exemplo.com\\",\\"role\\":\\"participant\\",\\"phone\\":\\"844466353\\",\\"verification_status\\":\\"approved\\",\\"balance\\":\\"0.00\\"}}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-07 15:26:11',
                'updated_at' => '2026-02-07 15:26:11',
            ),
            8 => 
            array (
                'id' => 9,
                'user_id' => 1,
                'action' => 'user_updated',
                'description' => 'Usuário Teste PowerShell Atualizado [MODIFICADO] atualizado pelo administrador',
                'metadata' => '"{\\"user_id\\":43,\\"changes\\":{\\"verification_status\\":\\"rejected\\"}}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-07 15:26:56',
                'updated_at' => '2026-02-07 15:26:56',
            ),
            9 => 
            array (
                'id' => 10,
                'user_id' => 1,
                'action' => 'user_updated',
                'description' => 'Usuário Teste PowerShell Atualizado [MODIFICADO] atualizado pelo administrador',
                'metadata' => '"{\\"user_id\\":43,\\"changes\\":[]}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-07 15:31:16',
                'updated_at' => '2026-02-07 15:31:16',
            ),
            10 => 
            array (
                'id' => 11,
                'user_id' => 1,
                'action' => 'user_deleted',
                'description' => 'Usuário Teste PowerShell Atualizado [MODIFICADO] excluído pelo administrador',
                'metadata' => '"{\\"user_id\\":\\"43\\"}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-07 15:31:16',
                'updated_at' => '2026-02-07 15:31:16',
            ),
            11 => 
            array (
                'id' => 12,
                'user_id' => 1,
                'action' => 'bulk_user_action',
                'description' => 'Ação em massa \'activate\' executada em 2 usuários',
                'metadata' => '"{\\"action\\":\\"activate\\",\\"success_count\\":2,\\"failed_count\\":0,\\"reason\\":\\"Teste\\"}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-07 15:31:17',
                'updated_at' => '2026-02-07 15:31:17',
            ),
            12 => 
            array (
                'id' => 13,
                'user_id' => 1,
                'action' => 'user_created',
                'description' => 'Usuário Teste Completo 174452 criado pelo administrador',
                'metadata' => '"{\\"user_id\\":44,\\"role\\":\\"participant\\"}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-07 15:44:55',
                'updated_at' => '2026-02-07 15:44:55',
            ),
            13 => 
            array (
                'id' => 14,
                'user_id' => 1,
                'action' => 'user_created',
                'description' => 'Usuário Teste Completo 174501 criado pelo administrador',
                'metadata' => '"{\\"user_id\\":45,\\"role\\":\\"participant\\"}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-07 15:45:02',
                'updated_at' => '2026-02-07 15:45:02',
            ),
            14 => 
            array (
                'id' => 15,
                'user_id' => 1,
                'action' => 'user_updated',
                'description' => 'Usuário Teste Completo 174501 atualizado pelo administrador',
                'metadata' => '"{\\"user_id\\":45,\\"changes\\":{\\"verification_status\\":\\"rejected\\"}}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-07 15:46:45',
                'updated_at' => '2026-02-07 15:46:45',
            ),
            15 => 
            array (
                'id' => 16,
                'user_id' => 1,
                'action' => 'user_updated',
                'description' => 'Usuário Teste Completo 174452 atualizado pelo administrador',
                'metadata' => '"{\\"user_id\\":44,\\"changes\\":{\\"verification_status\\":\\"rejected\\"}}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-07 15:46:53',
                'updated_at' => '2026-02-07 15:46:53',
            ),
            16 => 
            array (
                'id' => 17,
                'user_id' => 1,
                'action' => 'user_updated',
                'description' => 'Usuário Teste Completo 174501 atualizado pelo administrador',
                'metadata' => '"{\\"user_id\\":45,\\"changes\\":[]}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-07 15:47:59',
                'updated_at' => '2026-02-07 15:47:59',
            ),
            17 => 
            array (
                'id' => 18,
                'user_id' => 1,
                'action' => 'user_created',
                'description' => 'Usuário edilson Mutisse mutisse criado pelo administrador',
                'metadata' => '"{\\"user_id\\":46,\\"role\\":\\"admin\\"}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-07 16:50:53',
                'updated_at' => '2026-02-07 16:50:53',
            ),
            18 => 
            array (
                'id' => 19,
                'user_id' => 1,
                'action' => 'user_updated',
                'description' => 'Usuário edilson Mutisse mutisse atualizado pelo administrador',
                'metadata' => '"{\\"user_id\\":46,\\"changes\\":{\\"name\\":\\"edilson Mutisse mutisse\\",\\"email\\":\\"edilson.mutisse@uem.ac.mz\\",\\"role\\":\\"admin\\",\\"phone\\":\\"841234567\\",\\"verification_status\\":\\"approved\\"}}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-12 10:09:44',
                'updated_at' => '2026-02-12 10:09:44',
            ),
            19 => 
            array (
                'id' => 20,
                'user_id' => 1,
                'action' => 'user_updated',
                'description' => 'Usuário Teste Completo 174452 atualizado pelo administrador',
                'metadata' => '"{\\"user_id\\":44,\\"changes\\":{\\"verification_status\\":\\"approved\\"}}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-12 11:27:07',
                'updated_at' => '2026-02-12 11:27:07',
            ),
            20 => 
            array (
                'id' => 21,
                'user_id' => 1,
                'action' => 'user_updated',
                'description' => 'Usuário Participante 12 atualizado pelo administrador',
                'metadata' => '"{\\"user_id\\":34,\\"changes\\":{\\"verification_status\\":\\"rejected\\"}}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-12 12:02:26',
                'updated_at' => '2026-02-12 12:02:26',
            ),
            21 => 
            array (
                'id' => 22,
                'user_id' => 1,
                'action' => 'user_updated',
                'description' => 'Usuário Participante 11 atualizado pelo administrador',
                'metadata' => '"{\\"user_id\\":33,\\"changes\\":{\\"verification_status\\":\\"rejected\\"}}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-12 12:02:31',
                'updated_at' => '2026-02-12 12:02:31',
            ),
            22 => 
            array (
                'id' => 23,
                'user_id' => 1,
                'action' => 'user_updated',
                'description' => 'Usuário Respondente 4 atualizado pelo administrador',
                'metadata' => '"{\\"user_id\\":31,\\"changes\\":{\\"verification_status\\":\\"rejected\\"}}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-12 12:02:35',
                'updated_at' => '2026-02-12 12:02:35',
            ),
            23 => 
            array (
                'id' => 24,
                'user_id' => 1,
                'action' => 'user_updated',
                'description' => 'Usuário Respondente 5 atualizado pelo administrador',
                'metadata' => '"{\\"user_id\\":32,\\"changes\\":{\\"verification_status\\":\\"rejected\\"}}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-12 12:02:38',
                'updated_at' => '2026-02-12 12:02:38',
            ),
            24 => 
            array (
                'id' => 25,
                'user_id' => 1,
                'action' => 'user_updated',
                'description' => 'Usuário Respondente 1 atualizado pelo administrador',
                'metadata' => '"{\\"user_id\\":28,\\"changes\\":{\\"verification_status\\":\\"rejected\\"}}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-12 12:02:42',
                'updated_at' => '2026-02-12 12:02:42',
            ),
            25 => 
            array (
                'id' => 26,
                'user_id' => 1,
                'action' => 'user_updated',
                'description' => 'Usuário Participante 7 atualizado pelo administrador',
                'metadata' => '"{\\"user_id\\":24,\\"changes\\":{\\"verification_status\\":\\"rejected\\"}}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-12 12:02:48',
                'updated_at' => '2026-02-12 12:02:48',
            ),
            26 => 
            array (
                'id' => 27,
                'user_id' => 1,
                'action' => 'user_updated',
                'description' => 'Usuário Participante 8 atualizado pelo administrador',
                'metadata' => '"{\\"user_id\\":25,\\"changes\\":{\\"verification_status\\":\\"rejected\\"}}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-12 12:02:56',
                'updated_at' => '2026-02-12 12:02:56',
            ),
            27 => 
            array (
                'id' => 28,
                'user_id' => 1,
                'action' => 'user_deleted',
                'description' => 'Usuário Teste Completo 174501 excluído pelo administrador',
                'metadata' => '"{\\"user_id\\":\\"45\\"}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-12 12:32:35',
                'updated_at' => '2026-02-12 12:32:35',
            ),
            28 => 
            array (
                'id' => 29,
                'user_id' => 1,
                'action' => 'user_deleted',
                'description' => 'Usuário Teste Completo 174452 excluído pelo administrador',
                'metadata' => '"{\\"user_id\\":\\"44\\"}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-12 12:32:43',
                'updated_at' => '2026-02-12 12:32:43',
            ),
            29 => 
            array (
                'id' => 30,
                'user_id' => 1,
                'action' => 'user_deleted',
                'description' => 'Usuário Participante 19 excluído pelo administrador',
                'metadata' => '"{\\"user_id\\":\\"41\\"}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-12 12:32:52',
                'updated_at' => '2026-02-12 12:32:52',
            ),
            30 => 
            array (
                'id' => 31,
                'user_id' => 1,
                'action' => 'user_deleted',
                'description' => 'Usuário Participante 20 excluído pelo administrador',
                'metadata' => '"{\\"user_id\\":\\"42\\"}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-12 12:32:57',
                'updated_at' => '2026-02-12 12:32:57',
            ),
            31 => 
            array (
                'id' => 32,
                'user_id' => 1,
                'action' => 'user_deleted',
                'description' => 'Usuário Respondente 1 excluído pelo administrador',
                'metadata' => '"{\\"user_id\\":\\"28\\"}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-12 12:33:06',
                'updated_at' => '2026-02-12 12:33:06',
            ),
            32 => 
            array (
                'id' => 33,
                'user_id' => 1,
                'action' => 'user_deleted',
                'description' => 'Usuário Participante 8 excluído pelo administrador',
                'metadata' => '"{\\"user_id\\":\\"25\\"}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-12 12:33:12',
                'updated_at' => '2026-02-12 12:33:12',
            ),
            33 => 
            array (
                'id' => 34,
                'user_id' => 1,
                'action' => 'user_deleted',
                'description' => 'Usuário Participante 18 excluído pelo administrador',
                'metadata' => '"{\\"user_id\\":\\"40\\"}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-12 12:33:48',
                'updated_at' => '2026-02-12 12:33:48',
            ),
            34 => 
            array (
                'id' => 35,
                'user_id' => 1,
                'action' => 'user_deleted',
                'description' => 'Usuário Participante 11 excluído pelo administrador',
                'metadata' => '"{\\"user_id\\":\\"33\\"}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-12 12:33:55',
                'updated_at' => '2026-02-12 12:33:55',
            ),
            35 => 
            array (
                'id' => 36,
                'user_id' => 1,
                'action' => 'user_deleted',
                'description' => 'Usuário Participante 14 excluído pelo administrador',
                'metadata' => '"{\\"user_id\\":\\"36\\"}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-12 12:34:03',
                'updated_at' => '2026-02-12 12:34:03',
            ),
            36 => 
            array (
                'id' => 37,
                'user_id' => 1,
                'action' => 'user_deleted',
                'description' => 'Usuário Participante 17 excluído pelo administrador',
                'metadata' => '"{\\"user_id\\":\\"39\\"}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-12 12:34:22',
                'updated_at' => '2026-02-12 12:34:22',
            ),
            37 => 
            array (
                'id' => 38,
                'user_id' => 1,
                'action' => 'user_deleted',
                'description' => 'Usuário Respondente 5 excluído pelo administrador',
                'metadata' => '"{\\"user_id\\":\\"32\\"}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-12 12:34:29',
                'updated_at' => '2026-02-12 12:34:29',
            ),
            38 => 
            array (
                'id' => 39,
                'user_id' => 1,
                'action' => 'user_deleted',
                'description' => 'Usuário Participante 13 excluído pelo administrador',
                'metadata' => '"{\\"user_id\\":\\"35\\"}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-12 12:34:35',
                'updated_at' => '2026-02-12 12:34:35',
            ),
            39 => 
            array (
                'id' => 40,
                'user_id' => 1,
                'action' => 'user_deleted',
                'description' => 'Usuário Pesquisador Acadêmico excluído pelo administrador',
                'metadata' => '"{\\"user_id\\":\\"17\\"}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-12 12:34:50',
                'updated_at' => '2026-02-12 12:34:50',
            ),
            40 => 
            array (
                'id' => 41,
                'user_id' => 1,
                'action' => 'user_deleted',
                'description' => 'Usuário Participante 10 excluído pelo administrador',
                'metadata' => '"{\\"user_id\\":\\"27\\"}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-12 12:34:58',
                'updated_at' => '2026-02-12 12:34:58',
            ),
            41 => 
            array (
                'id' => 42,
                'user_id' => 1,
                'action' => 'user_deleted',
                'description' => 'Usuário Participante 2 excluído pelo administrador',
                'metadata' => '"{\\"user_id\\":\\"19\\"}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-12 12:35:07',
                'updated_at' => '2026-02-12 12:35:07',
            ),
            42 => 
            array (
                'id' => 43,
                'user_id' => 1,
                'action' => 'user_deleted',
                'description' => 'Usuário Participante 1 excluído pelo administrador',
                'metadata' => '"{\\"user_id\\":\\"18\\"}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-12 12:35:12',
                'updated_at' => '2026-02-12 12:35:12',
            ),
            43 => 
            array (
                'id' => 44,
                'user_id' => 1,
                'action' => 'user_deleted',
                'description' => 'Usuário Participante 6 excluído pelo administrador',
                'metadata' => '"{\\"user_id\\":\\"23\\"}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-12 12:35:19',
                'updated_at' => '2026-02-12 12:35:19',
            ),
            44 => 
            array (
                'id' => 45,
                'user_id' => 1,
                'action' => 'user_deleted',
                'description' => 'Usuário Participante 15 excluído pelo administrador',
                'metadata' => '"{\\"user_id\\":\\"37\\"}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-12 12:35:26',
                'updated_at' => '2026-02-12 12:35:26',
            ),
            45 => 
            array (
                'id' => 46,
                'user_id' => 1,
                'action' => 'user_deleted',
                'description' => 'Usuário Participante 12 excluído pelo administrador',
                'metadata' => '"{\\"user_id\\":\\"34\\"}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-12 12:35:32',
                'updated_at' => '2026-02-12 12:35:32',
            ),
            46 => 
            array (
                'id' => 47,
                'user_id' => 1,
                'action' => 'user_deleted',
                'description' => 'Usuário Respondente 3 excluído pelo administrador',
                'metadata' => '"{\\"user_id\\":\\"30\\"}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-12 12:35:37',
                'updated_at' => '2026-02-12 12:35:37',
            ),
            47 => 
            array (
                'id' => 48,
                'user_id' => 1,
                'action' => 'user_deleted',
                'description' => 'Usuário Participante 16 excluído pelo administrador',
                'metadata' => '"{\\"user_id\\":\\"38\\"}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-12 12:35:40',
                'updated_at' => '2026-02-12 12:35:40',
            ),
            48 => 
            array (
                'id' => 49,
                'user_id' => 1,
                'action' => 'user_deleted',
                'description' => 'Usuário Respondente 2 excluído pelo administrador',
                'metadata' => '"{\\"user_id\\":\\"29\\"}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-12 12:35:46',
                'updated_at' => '2026-02-12 12:35:46',
            ),
            49 => 
            array (
                'id' => 50,
                'user_id' => 1,
                'action' => 'user_deleted',
                'description' => 'Usuário Participante 9 excluído pelo administrador',
                'metadata' => '"{\\"user_id\\":\\"26\\"}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-12 12:35:50',
                'updated_at' => '2026-02-12 12:35:50',
            ),
            50 => 
            array (
                'id' => 51,
                'user_id' => 1,
                'action' => 'user_deleted',
                'description' => 'Usuário Respondente 4 excluído pelo administrador',
                'metadata' => '"{\\"user_id\\":\\"31\\"}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-12 12:35:54',
                'updated_at' => '2026-02-12 12:35:54',
            ),
            51 => 
            array (
                'id' => 52,
                'user_id' => 1,
                'action' => 'user_deleted',
                'description' => 'Usuário Participante 3 excluído pelo administrador',
                'metadata' => '"{\\"user_id\\":\\"20\\"}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-12 12:36:00',
                'updated_at' => '2026-02-12 12:36:00',
            ),
            52 => 
            array (
                'id' => 53,
                'user_id' => 1,
                'action' => 'user_deleted',
                'description' => 'Usuário Participante 7 excluído pelo administrador',
                'metadata' => '"{\\"user_id\\":\\"24\\"}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-12 12:36:04',
                'updated_at' => '2026-02-12 12:36:04',
            ),
            53 => 
            array (
                'id' => 54,
                'user_id' => 1,
                'action' => 'user_deleted',
                'description' => 'Usuário Participante 4 excluído pelo administrador',
                'metadata' => '"{\\"user_id\\":\\"21\\"}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-12 12:36:08',
                'updated_at' => '2026-02-12 12:36:08',
            ),
            54 => 
            array (
                'id' => 55,
                'user_id' => 1,
                'action' => 'user_deleted',
                'description' => 'Usuário Participante 5 excluído pelo administrador',
                'metadata' => '"{\\"user_id\\":\\"22\\"}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-12 12:36:13',
                'updated_at' => '2026-02-12 12:36:13',
            ),
            55 => 
            array (
                'id' => 56,
                'user_id' => 1,
                'action' => 'user_updated',
                'description' => 'Usuário Marta José Amisse atualizado pelo administrador',
                'metadata' => '"{\\"user_id\\":16,\\"changes\\":{\\"verification_status\\":\\"approved\\"}}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-12 12:37:02',
                'updated_at' => '2026-02-12 12:37:02',
            ),
            56 => 
            array (
                'id' => 57,
                'user_id' => 1,
                'action' => 'user_deleted',
                'description' => 'Usuário edilson Mutisse mutisse excluído pelo administrador',
                'metadata' => '"{\\"user_id\\":\\"46\\"}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-12 12:51:53',
                'updated_at' => '2026-02-12 12:51:53',
            ),
            57 => 
            array (
                'id' => 58,
                'user_id' => 1,
                'action' => 'user_created',
                'description' => 'Usuário edilson Mutisse criado pelo administrador',
                'metadata' => '"{\\"user_id\\":47,\\"role\\":\\"admin\\"}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-12 12:53:04',
                'updated_at' => '2026-02-12 12:53:04',
            ),
            58 => 
            array (
                'id' => 59,
                'user_id' => 1,
                'action' => 'user_updated',
                'description' => 'Usuário edilson Mutisse atualizado pelo administrador',
                'metadata' => '"{\\"user_id\\":47,\\"changes\\":{\\"name\\":\\"edilson Mutisse\\",\\"email\\":\\"edilson.mutisse@mozpesquisa.ac.mz\\",\\"role\\":\\"admin\\",\\"phone\\":\\"841234567\\",\\"verification_status\\":\\"approved\\"}}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-12 21:39:12',
                'updated_at' => '2026-02-12 21:39:12',
            ),
            59 => 
            array (
                'id' => 60,
                'user_id' => 1,
                'action' => 'user_updated',
                'description' => 'Usuário edilson Mutisse atualizado pelo administrador',
                'metadata' => '"{\\"user_id\\":47,\\"changes\\":{\\"name\\":\\"edilson Mutisse\\",\\"email\\":\\"edilson.mutisse@mozpesquisa.ac.mz\\",\\"role\\":\\"admin\\",\\"phone\\":\\"841234567\\",\\"verification_status\\":\\"approved\\"}}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-12 21:39:23',
                'updated_at' => '2026-02-12 21:39:23',
            ),
            60 => 
            array (
                'id' => 61,
                'user_id' => 1,
                'action' => 'user_deleted',
                'description' => 'Usuário edilson Mutisse excluído pelo administrador',
                'metadata' => '"{\\"user_id\\":\\"47\\"}"',
                'ip_address' => NULL,
                'user_agent' => NULL,
                'created_at' => '2026-02-15 04:31:29',
                'updated_at' => '2026-02-15 04:31:29',
            ),
        ));
        
        
    }
}