<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class NotificationsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('notifications')->delete();

        \DB::table('notifications')->insert(array (
            0 =>
            array (
                'id' => 128,
                'user_id' => 10,
                'type' => 'withdrawal_requested',
                'title' => 'Solicitação de Saque',
                'message' => 'Sua solicitação de saque de 50.00 MZN foi recebida e está em análise.',
                'icon' => NULL,
                'action_url' => NULL,
                'action_label' => NULL,
                'is_read' => 1,
                'read_at' => '2026-02-07 07:45:41',
                'expires_at' => NULL,
                'priority' => 1,
                'data' => '"{\\"transaction_id\\":3,\\"amount\\":50,\\"payment_method\\":\\"mpesa\\"}"',
                'created_at' => '2026-02-07 05:46:13',
                'updated_at' => '2026-02-07 07:45:41',
            ),
            1 =>
            array (
                'id' => 2,
                'user_id' => 2,
                'type' => 'survey_response',
                'title' => 'Nova resposta recebida',
                'message' => 'Sua pesquisa recebeu uma nova resposta. Total: 45/50 respostas.',
                'icon' => 'assignment_turned_in',
                'action_url' => '/dashboard',
                'action_label' => 'Ver detalhes',
                'is_read' => 1,
                'read_at' => '2026-02-06 06:04:45',
                'expires_at' => '2026-03-07 15:46:49',
                'priority' => 1,
                'data' => '{"survey_id": 5, "response_count": 45}',
                'created_at' => '2026-02-05 09:46:49',
                'updated_at' => '2026-02-06 06:04:45',
            ),
            2 =>
            array (
                'id' => 3,
                'user_id' => 2,
                'type' => 'payment_received',
                'title' => 'Pagamento recebido',
                'message' => 'Você recebeu MZN 250.00 pelas respostas da sua pesquisa.',
                'icon' => 'payments',
                'action_url' => '/dashboard',
                'action_label' => 'Ver detalhes',
                'is_read' => 1,
                'read_at' => '2026-02-06 06:04:45',
                'expires_at' => '2026-03-07 15:46:49',
                'priority' => 2,
                'data' => '{"amount": 250, "currency": "MZN"}',
                'created_at' => '2026-02-04 15:46:49',
                'updated_at' => '2026-02-06 06:04:45',
            ),
            3 =>
            array (
                'id' => 4,
                'user_id' => 2,
                'type' => 'survey_expiring',
                'title' => 'Pesquisa expirando',
                'message' => 'Sua pesquisa \'Consumo de Energia Residencial\' expira em 3 dias.',
                'icon' => 'schedule',
                'action_url' => '/dashboard',
                'action_label' => 'Ver detalhes',
                'is_read' => 1,
                'read_at' => '2026-02-06 06:04:45',
                'expires_at' => '2026-03-07 15:46:49',
                'priority' => 3,
                'data' => '{"days_left": 3, "survey_id": 9}',
                'created_at' => '2026-02-03 15:46:49',
                'updated_at' => '2026-02-06 06:04:45',
            ),
            4 =>
            array (
                'id' => 5,
                'user_id' => 2,
                'type' => 'survey_completed',
                'title' => 'Meta atingida!',
                'message' => 'Parabéns! Sua pesquisa atingiu 100% das respostas necessárias.',
                'icon' => 'task_alt',
                'action_url' => '/dashboard',
                'action_label' => 'Ver detalhes',
                'is_read' => 1,
                'read_at' => '2026-02-02 15:46:49',
                'expires_at' => '2026-03-07 15:46:49',
                'priority' => 1,
                'data' => '{"survey_id": 12}',
                'created_at' => '2026-02-01 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            5 =>
            array (
                'id' => 6,
                'user_id' => 2,
                'type' => 'withdrawal_processed',
                'title' => 'Saque realizado',
                'message' => 'Seu saque de MZN 500.00 foi processado com sucesso.',
                'icon' => 'account_balance_wallet',
                'action_url' => '/dashboard',
                'action_label' => 'Ver detalhes',
                'is_read' => 1,
                'read_at' => '2026-01-31 15:46:49',
                'expires_at' => '2026-03-07 15:46:49',
                'priority' => 2,
                'data' => '{"amount": 500}',
                'created_at' => '2026-01-31 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            6 =>
            array (
                'id' => 7,
                'user_id' => 2,
                'type' => 'new_feature',
                'title' => 'Nova funcionalidade',
                'message' => 'Agora você pode exportar relatórios em PDF. Experimente!',
                'icon' => 'new_releases',
                'action_url' => '/dashboard',
                'action_label' => 'Ver detalhes',
                'is_read' => 1,
                'read_at' => '2026-02-06 06:04:45',
                'expires_at' => '2026-03-07 15:46:49',
                'priority' => 1,
                'data' => '{"feature": "export_pdf"}',
                'created_at' => '2026-02-04 15:46:49',
                'updated_at' => '2026-02-06 06:04:45',
            ),
            7 =>
            array (
                'id' => 8,
                'user_id' => 2,
                'type' => 'system_maintenance',
                'title' => 'Manutenção programada',
                'message' => 'O sistema estará indisponível das 02:00 às 04:00 para manutenção.',
                'icon' => 'build',
                'action_url' => '/dashboard',
                'action_label' => 'Ver detalhes',
                'is_read' => 1,
                'read_at' => '2026-02-06 06:04:45',
                'expires_at' => '2026-03-07 15:46:49',
                'priority' => 2,
                'data' => '{"end_time": "04:00", "start_time": "02:00"}',
                'created_at' => '2026-02-03 15:46:49',
                'updated_at' => '2026-02-06 06:04:45',
            ),
            8 =>
            array (
                'id' => 9,
                'user_id' => 3,
                'type' => 'survey_approved',
                'title' => 'Pesquisa aprovada!',
                'message' => 'Sua pesquisa \'Hábitos de Leitura em Universidades Moçambicanas\' foi aprovada e está publicada.',
                'icon' => 'check_circle',
                'action_url' => '/dashboard',
                'action_label' => 'Ver detalhes',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-03-07 15:46:49',
                'priority' => 2,
                'data' => '{"action": "view_survey", "survey_id": 5}',
                'created_at' => '2026-02-05 13:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            9 =>
            array (
                'id' => 10,
                'user_id' => 3,
                'type' => 'survey_response',
                'title' => 'Nova resposta recebida',
                'message' => 'Sua pesquisa recebeu uma nova resposta. Total: 45/50 respostas.',
                'icon' => 'assignment_turned_in',
                'action_url' => '/dashboard',
                'action_label' => 'Ver detalhes',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-03-07 15:46:49',
                'priority' => 1,
                'data' => '{"survey_id": 3, "response_count": 45}',
                'created_at' => '2026-02-05 09:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            10 =>
            array (
                'id' => 11,
                'user_id' => 3,
                'type' => 'payment_received',
                'title' => 'Pagamento recebido',
                'message' => 'Você recebeu MZN 250.00 pelas respostas da sua pesquisa.',
                'icon' => 'payments',
                'action_url' => '/dashboard',
                'action_label' => 'Ver detalhes',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-03-07 15:46:49',
                'priority' => 2,
                'data' => '{"amount": 250, "currency": "MZN"}',
                'created_at' => '2026-02-04 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            11 =>
            array (
                'id' => 12,
                'user_id' => 3,
                'type' => 'survey_expiring',
                'title' => 'Pesquisa expirando',
                'message' => 'Sua pesquisa \'Consumo de Energia Residencial\' expira em 3 dias.',
                'icon' => 'schedule',
                'action_url' => '/dashboard',
                'action_label' => 'Ver detalhes',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-03-07 15:46:49',
                'priority' => 3,
                'data' => '{"days_left": 3, "survey_id": 9}',
                'created_at' => '2026-02-03 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            12 =>
            array (
                'id' => 13,
                'user_id' => 3,
                'type' => 'survey_completed',
                'title' => 'Meta atingida!',
                'message' => 'Parabéns! Sua pesquisa atingiu 100% das respostas necessárias.',
                'icon' => 'task_alt',
                'action_url' => '/dashboard',
                'action_label' => 'Ver detalhes',
                'is_read' => 1,
                'read_at' => '2026-02-02 15:46:49',
                'expires_at' => '2026-03-07 15:46:49',
                'priority' => 1,
                'data' => '{"survey_id": 11}',
                'created_at' => '2026-02-01 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            13 =>
            array (
                'id' => 14,
                'user_id' => 3,
                'type' => 'withdrawal_processed',
                'title' => 'Saque realizado',
                'message' => 'Seu saque de MZN 500.00 foi processado com sucesso.',
                'icon' => 'account_balance_wallet',
                'action_url' => '/dashboard',
                'action_label' => 'Ver detalhes',
                'is_read' => 1,
                'read_at' => '2026-01-31 15:46:49',
                'expires_at' => '2026-03-07 15:46:49',
                'priority' => 2,
                'data' => '{"amount": 500}',
                'created_at' => '2026-01-31 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            14 =>
            array (
                'id' => 15,
                'user_id' => 3,
                'type' => 'new_feature',
                'title' => 'Nova funcionalidade',
                'message' => 'Agora você pode exportar relatórios em PDF. Experimente!',
                'icon' => 'new_releases',
                'action_url' => '/dashboard',
                'action_label' => 'Ver detalhes',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-03-07 15:46:49',
                'priority' => 1,
                'data' => '{"feature": "export_pdf"}',
                'created_at' => '2026-02-04 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            15 =>
            array (
                'id' => 16,
                'user_id' => 3,
                'type' => 'system_maintenance',
                'title' => 'Manutenção programada',
                'message' => 'O sistema estará indisponível das 02:00 às 04:00 para manutenção.',
                'icon' => 'build',
                'action_url' => '/dashboard',
                'action_label' => 'Ver detalhes',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-03-07 15:46:49',
                'priority' => 2,
                'data' => '{"end_time": "04:00", "start_time": "02:00"}',
                'created_at' => '2026-02-03 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            16 =>
            array (
                'id' => 17,
                'user_id' => 4,
                'type' => 'survey_approved',
                'title' => 'Pesquisa aprovada!',
                'message' => 'Sua pesquisa \'Hábitos de Leitura em Universidades Moçambicanas\' foi aprovada e está publicada.',
                'icon' => 'check_circle',
                'action_url' => '/dashboard',
                'action_label' => 'Ver detalhes',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-03-07 15:46:49',
                'priority' => 2,
                'data' => '{"action": "view_survey", "survey_id": 3}',
                'created_at' => '2026-02-05 13:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            17 =>
            array (
                'id' => 18,
                'user_id' => 4,
                'type' => 'survey_response',
                'title' => 'Nova resposta recebida',
                'message' => 'Sua pesquisa recebeu uma nova resposta. Total: 45/50 respostas.',
                'icon' => 'assignment_turned_in',
                'action_url' => '/dashboard',
                'action_label' => 'Ver detalhes',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-03-07 15:46:49',
                'priority' => 1,
                'data' => '{"survey_id": 2, "response_count": 45}',
                'created_at' => '2026-02-05 09:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            18 =>
            array (
                'id' => 19,
                'user_id' => 4,
                'type' => 'payment_received',
                'title' => 'Pagamento recebido',
                'message' => 'Você recebeu MZN 250.00 pelas respostas da sua pesquisa.',
                'icon' => 'payments',
                'action_url' => '/dashboard',
                'action_label' => 'Ver detalhes',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-03-07 15:46:49',
                'priority' => 2,
                'data' => '{"amount": 250, "currency": "MZN"}',
                'created_at' => '2026-02-04 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            19 =>
            array (
                'id' => 20,
                'user_id' => 4,
                'type' => 'survey_expiring',
                'title' => 'Pesquisa expirando',
                'message' => 'Sua pesquisa \'Consumo de Energia Residencial\' expira em 3 dias.',
                'icon' => 'schedule',
                'action_url' => '/dashboard',
                'action_label' => 'Ver detalhes',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-03-07 15:46:49',
                'priority' => 3,
                'data' => '{"days_left": 3, "survey_id": 9}',
                'created_at' => '2026-02-03 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            20 =>
            array (
                'id' => 21,
                'user_id' => 4,
                'type' => 'survey_completed',
                'title' => 'Meta atingida!',
                'message' => 'Parabéns! Sua pesquisa atingiu 100% das respostas necessárias.',
                'icon' => 'task_alt',
                'action_url' => '/dashboard',
                'action_label' => 'Ver detalhes',
                'is_read' => 1,
                'read_at' => '2026-02-02 15:46:49',
                'expires_at' => '2026-03-07 15:46:49',
                'priority' => 1,
                'data' => '{"survey_id": 12}',
                'created_at' => '2026-02-01 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            21 =>
            array (
                'id' => 22,
                'user_id' => 4,
                'type' => 'withdrawal_processed',
                'title' => 'Saque realizado',
                'message' => 'Seu saque de MZN 500.00 foi processado com sucesso.',
                'icon' => 'account_balance_wallet',
                'action_url' => '/dashboard',
                'action_label' => 'Ver detalhes',
                'is_read' => 1,
                'read_at' => '2026-01-31 15:46:49',
                'expires_at' => '2026-03-07 15:46:49',
                'priority' => 2,
                'data' => '{"amount": 500}',
                'created_at' => '2026-01-31 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            22 =>
            array (
                'id' => 23,
                'user_id' => 4,
                'type' => 'new_feature',
                'title' => 'Nova funcionalidade',
                'message' => 'Agora você pode exportar relatórios em PDF. Experimente!',
                'icon' => 'new_releases',
                'action_url' => '/dashboard',
                'action_label' => 'Ver detalhes',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-03-07 15:46:49',
                'priority' => 1,
                'data' => '{"feature": "export_pdf"}',
                'created_at' => '2026-02-04 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            23 =>
            array (
                'id' => 24,
                'user_id' => 4,
                'type' => 'system_maintenance',
                'title' => 'Manutenção programada',
                'message' => 'O sistema estará indisponível das 02:00 às 04:00 para manutenção.',
                'icon' => 'build',
                'action_url' => '/dashboard',
                'action_label' => 'Ver detalhes',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-03-07 15:46:49',
                'priority' => 2,
                'data' => '{"end_time": "04:00", "start_time": "02:00"}',
                'created_at' => '2026-02-03 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            24 =>
            array (
                'id' => 25,
                'user_id' => 5,
                'type' => 'survey_approved',
                'title' => 'Pesquisa aprovada!',
                'message' => 'Sua pesquisa \'Hábitos de Leitura em Universidades Moçambicanas\' foi aprovada e está publicada.',
                'icon' => 'check_circle',
                'action_url' => '/dashboard',
                'action_label' => 'Ver detalhes',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-03-07 15:46:49',
                'priority' => 2,
                'data' => '{"action": "view_survey", "survey_id": 2}',
                'created_at' => '2026-02-05 13:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            25 =>
            array (
                'id' => 26,
                'user_id' => 5,
                'type' => 'survey_response',
                'title' => 'Nova resposta recebida',
                'message' => 'Sua pesquisa recebeu uma nova resposta. Total: 45/50 respostas.',
                'icon' => 'assignment_turned_in',
                'action_url' => '/dashboard',
                'action_label' => 'Ver detalhes',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-03-07 15:46:49',
                'priority' => 1,
                'data' => '{"survey_id": 2, "response_count": 45}',
                'created_at' => '2026-02-05 09:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            26 =>
            array (
                'id' => 27,
                'user_id' => 5,
                'type' => 'payment_received',
                'title' => 'Pagamento recebido',
                'message' => 'Você recebeu MZN 250.00 pelas respostas da sua pesquisa.',
                'icon' => 'payments',
                'action_url' => '/dashboard',
                'action_label' => 'Ver detalhes',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-03-07 15:46:49',
                'priority' => 2,
                'data' => '{"amount": 250, "currency": "MZN"}',
                'created_at' => '2026-02-04 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            27 =>
            array (
                'id' => 28,
                'user_id' => 5,
                'type' => 'survey_expiring',
                'title' => 'Pesquisa expirando',
                'message' => 'Sua pesquisa \'Consumo de Energia Residencial\' expira em 3 dias.',
                'icon' => 'schedule',
                'action_url' => '/dashboard',
                'action_label' => 'Ver detalhes',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-03-07 15:46:49',
                'priority' => 3,
                'data' => '{"days_left": 3, "survey_id": 6}',
                'created_at' => '2026-02-03 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            28 =>
            array (
                'id' => 29,
                'user_id' => 5,
                'type' => 'survey_completed',
                'title' => 'Meta atingida!',
                'message' => 'Parabéns! Sua pesquisa atingiu 100% das respostas necessárias.',
                'icon' => 'task_alt',
                'action_url' => '/dashboard',
                'action_label' => 'Ver detalhes',
                'is_read' => 1,
                'read_at' => '2026-02-02 15:46:49',
                'expires_at' => '2026-03-07 15:46:49',
                'priority' => 1,
                'data' => '{"survey_id": 15}',
                'created_at' => '2026-02-01 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            29 =>
            array (
                'id' => 30,
                'user_id' => 5,
                'type' => 'withdrawal_processed',
                'title' => 'Saque realizado',
                'message' => 'Seu saque de MZN 500.00 foi processado com sucesso.',
                'icon' => 'account_balance_wallet',
                'action_url' => '/dashboard',
                'action_label' => 'Ver detalhes',
                'is_read' => 1,
                'read_at' => '2026-01-31 15:46:49',
                'expires_at' => '2026-03-07 15:46:49',
                'priority' => 2,
                'data' => '{"amount": 500}',
                'created_at' => '2026-01-31 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            30 =>
            array (
                'id' => 31,
                'user_id' => 5,
                'type' => 'new_feature',
                'title' => 'Nova funcionalidade',
                'message' => 'Agora você pode exportar relatórios em PDF. Experimente!',
                'icon' => 'new_releases',
                'action_url' => '/dashboard',
                'action_label' => 'Ver detalhes',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-03-07 15:46:49',
                'priority' => 1,
                'data' => '{"feature": "export_pdf"}',
                'created_at' => '2026-02-04 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            31 =>
            array (
                'id' => 32,
                'user_id' => 5,
                'type' => 'system_maintenance',
                'title' => 'Manutenção programada',
                'message' => 'O sistema estará indisponível das 02:00 às 04:00 para manutenção.',
                'icon' => 'build',
                'action_url' => '/dashboard',
                'action_label' => 'Ver detalhes',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-03-07 15:46:49',
                'priority' => 2,
                'data' => '{"end_time": "04:00", "start_time": "02:00"}',
                'created_at' => '2026-02-03 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            32 =>
            array (
                'id' => 33,
                'user_id' => 6,
                'type' => 'survey_approved',
                'title' => 'Pesquisa aprovada!',
                'message' => 'Sua pesquisa \'Hábitos de Leitura em Universidades Moçambicanas\' foi aprovada e está publicada.',
                'icon' => 'check_circle',
                'action_url' => '/dashboard',
                'action_label' => 'Ver detalhes',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-03-07 15:46:49',
                'priority' => 2,
                'data' => '{"action": "view_survey", "survey_id": 2}',
                'created_at' => '2026-02-05 13:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            33 =>
            array (
                'id' => 34,
                'user_id' => 6,
                'type' => 'survey_response',
                'title' => 'Nova resposta recebida',
                'message' => 'Sua pesquisa recebeu uma nova resposta. Total: 45/50 respostas.',
                'icon' => 'assignment_turned_in',
                'action_url' => '/dashboard',
                'action_label' => 'Ver detalhes',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-03-07 15:46:49',
                'priority' => 1,
                'data' => '{"survey_id": 4, "response_count": 45}',
                'created_at' => '2026-02-05 09:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            34 =>
            array (
                'id' => 35,
                'user_id' => 6,
                'type' => 'payment_received',
                'title' => 'Pagamento recebido',
                'message' => 'Você recebeu MZN 250.00 pelas respostas da sua pesquisa.',
                'icon' => 'payments',
                'action_url' => '/dashboard',
                'action_label' => 'Ver detalhes',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-03-07 15:46:49',
                'priority' => 2,
                'data' => '{"amount": 250, "currency": "MZN"}',
                'created_at' => '2026-02-04 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            35 =>
            array (
                'id' => 36,
                'user_id' => 6,
                'type' => 'survey_expiring',
                'title' => 'Pesquisa expirando',
                'message' => 'Sua pesquisa \'Consumo de Energia Residencial\' expira em 3 dias.',
                'icon' => 'schedule',
                'action_url' => '/dashboard',
                'action_label' => 'Ver detalhes',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-03-07 15:46:49',
                'priority' => 3,
                'data' => '{"days_left": 3, "survey_id": 6}',
                'created_at' => '2026-02-03 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            36 =>
            array (
                'id' => 37,
                'user_id' => 6,
                'type' => 'survey_completed',
                'title' => 'Meta atingida!',
                'message' => 'Parabéns! Sua pesquisa atingiu 100% das respostas necessárias.',
                'icon' => 'task_alt',
                'action_url' => '/dashboard',
                'action_label' => 'Ver detalhes',
                'is_read' => 1,
                'read_at' => '2026-02-02 15:46:49',
                'expires_at' => '2026-03-07 15:46:49',
                'priority' => 1,
                'data' => '{"survey_id": 13}',
                'created_at' => '2026-02-01 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            37 =>
            array (
                'id' => 38,
                'user_id' => 6,
                'type' => 'withdrawal_processed',
                'title' => 'Saque realizado',
                'message' => 'Seu saque de MZN 500.00 foi processado com sucesso.',
                'icon' => 'account_balance_wallet',
                'action_url' => '/dashboard',
                'action_label' => 'Ver detalhes',
                'is_read' => 1,
                'read_at' => '2026-01-31 15:46:49',
                'expires_at' => '2026-03-07 15:46:49',
                'priority' => 2,
                'data' => '{"amount": 500}',
                'created_at' => '2026-01-31 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            38 =>
            array (
                'id' => 39,
                'user_id' => 6,
                'type' => 'new_feature',
                'title' => 'Nova funcionalidade',
                'message' => 'Agora você pode exportar relatórios em PDF. Experimente!',
                'icon' => 'new_releases',
                'action_url' => '/dashboard',
                'action_label' => 'Ver detalhes',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-03-07 15:46:49',
                'priority' => 1,
                'data' => '{"feature": "export_pdf"}',
                'created_at' => '2026-02-04 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            39 =>
            array (
                'id' => 40,
                'user_id' => 6,
                'type' => 'system_maintenance',
                'title' => 'Manutenção programada',
                'message' => 'O sistema estará indisponível das 02:00 às 04:00 para manutenção.',
                'icon' => 'build',
                'action_url' => '/dashboard',
                'action_label' => 'Ver detalhes',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-03-07 15:46:49',
                'priority' => 2,
                'data' => '{"end_time": "04:00", "start_time": "02:00"}',
                'created_at' => '2026-02-03 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            40 =>
            array (
                'id' => 41,
                'user_id' => 16,
                'type' => 'survey_approved',
                'title' => 'Pesquisa aprovada!',
                'message' => 'Sua pesquisa \'Hábitos de Leitura em Universidades Moçambicanas\' foi aprovada e está publicada.',
                'icon' => 'check_circle',
                'action_url' => '/dashboard',
                'action_label' => 'Ver detalhes',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-03-07 15:46:49',
                'priority' => 2,
                'data' => '{"action": "view_survey", "survey_id": 5}',
                'created_at' => '2026-02-05 13:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            41 =>
            array (
                'id' => 42,
                'user_id' => 16,
                'type' => 'survey_response',
                'title' => 'Nova resposta recebida',
                'message' => 'Sua pesquisa recebeu uma nova resposta. Total: 45/50 respostas.',
                'icon' => 'assignment_turned_in',
                'action_url' => '/dashboard',
                'action_label' => 'Ver detalhes',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-03-07 15:46:49',
                'priority' => 1,
                'data' => '{"survey_id": 2, "response_count": 45}',
                'created_at' => '2026-02-05 09:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            42 =>
            array (
                'id' => 43,
                'user_id' => 16,
                'type' => 'payment_received',
                'title' => 'Pagamento recebido',
                'message' => 'Você recebeu MZN 250.00 pelas respostas da sua pesquisa.',
                'icon' => 'payments',
                'action_url' => '/dashboard',
                'action_label' => 'Ver detalhes',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-03-07 15:46:49',
                'priority' => 2,
                'data' => '{"amount": 250, "currency": "MZN"}',
                'created_at' => '2026-02-04 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            43 =>
            array (
                'id' => 44,
                'user_id' => 16,
                'type' => 'survey_expiring',
                'title' => 'Pesquisa expirando',
                'message' => 'Sua pesquisa \'Consumo de Energia Residencial\' expira em 3 dias.',
                'icon' => 'schedule',
                'action_url' => '/dashboard',
                'action_label' => 'Ver detalhes',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-03-07 15:46:49',
                'priority' => 3,
                'data' => '{"days_left": 3, "survey_id": 10}',
                'created_at' => '2026-02-03 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            44 =>
            array (
                'id' => 45,
                'user_id' => 16,
                'type' => 'survey_completed',
                'title' => 'Meta atingida!',
                'message' => 'Parabéns! Sua pesquisa atingiu 100% das respostas necessárias.',
                'icon' => 'task_alt',
                'action_url' => '/dashboard',
                'action_label' => 'Ver detalhes',
                'is_read' => 1,
                'read_at' => '2026-02-02 15:46:49',
                'expires_at' => '2026-03-07 15:46:49',
                'priority' => 1,
                'data' => '{"survey_id": 14}',
                'created_at' => '2026-02-01 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            45 =>
            array (
                'id' => 46,
                'user_id' => 16,
                'type' => 'withdrawal_processed',
                'title' => 'Saque realizado',
                'message' => 'Seu saque de MZN 500.00 foi processado com sucesso.',
                'icon' => 'account_balance_wallet',
                'action_url' => '/dashboard',
                'action_label' => 'Ver detalhes',
                'is_read' => 1,
                'read_at' => '2026-01-31 15:46:49',
                'expires_at' => '2026-03-07 15:46:49',
                'priority' => 2,
                'data' => '{"amount": 500}',
                'created_at' => '2026-01-31 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            46 =>
            array (
                'id' => 47,
                'user_id' => 16,
                'type' => 'new_feature',
                'title' => 'Nova funcionalidade',
                'message' => 'Agora você pode exportar relatórios em PDF. Experimente!',
                'icon' => 'new_releases',
                'action_url' => '/dashboard',
                'action_label' => 'Ver detalhes',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-03-07 15:46:49',
                'priority' => 1,
                'data' => '{"feature": "export_pdf"}',
                'created_at' => '2026-02-04 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            47 =>
            array (
                'id' => 48,
                'user_id' => 16,
                'type' => 'system_maintenance',
                'title' => 'Manutenção programada',
                'message' => 'O sistema estará indisponível das 02:00 às 04:00 para manutenção.',
                'icon' => 'build',
                'action_url' => '/dashboard',
                'action_label' => 'Ver detalhes',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-03-07 15:46:49',
                'priority' => 2,
                'data' => '{"end_time": "04:00", "start_time": "02:00"}',
                'created_at' => '2026-02-03 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            48 =>
            array (
                'id' => 49,
                'user_id' => 7,
                'type' => 'survey_available',
                'title' => 'Nova pesquisa disponível',
                'message' => 'Pesquisa sobre hábitos de consumo - Ganhe MZN 30 por responder.',
                'icon' => 'assignment',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 1,
                'data' => '{"reward": 30, "survey_id": 20}',
                'created_at' => '2026-02-05 14:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            49 =>
            array (
                'id' => 50,
                'user_id' => 7,
                'type' => 'survey_available',
                'title' => 'Pesquisa compatível com seu perfil',
                'message' => 'Pesquisa sobre educação online para moradores de Maputo Cidade',
                'icon' => 'assignment',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 1,
                'data' => '{"reward": 25, "survey_id": 23}',
                'created_at' => '2026-02-05 11:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            50 =>
            array (
                'id' => 51,
                'user_id' => 7,
                'type' => 'bonus_received',
                'title' => 'Bônus recebido!',
                'message' => 'Você ganhou um bônus de MZN 10 por responder 5 pesquisas este mês.',
                'icon' => 'card_giftcard',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 2,
                'data' => '{"amount": 10, "reason": "fidelity"}',
                'created_at' => '2026-02-04 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            51 =>
            array (
                'id' => 52,
                'user_id' => 7,
                'type' => 'response_completed',
                'title' => 'Resposta completada',
                'message' => 'Você completou a pesquisa "Tecnologia na Educação" - MZN 25 creditado.',
                'icon' => 'done_all',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 1,
                'read_at' => '2026-02-03 15:46:49',
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 1,
                'data' => '{"amount": 25, "survey_id": 27}',
                'created_at' => '2026-02-03 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            52 =>
            array (
                'id' => 53,
                'user_id' => 7,
                'type' => 'payment_credited',
                'title' => 'Pagamento creditado',
                'message' => 'Recebeu MZN 75.00 por pesquisas respondidas.',
                'icon' => 'payments',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 1,
                'read_at' => '2026-02-02 15:46:49',
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 2,
                'data' => '{"amount": 75}',
                'created_at' => '2026-02-02 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            53 =>
            array (
                'id' => 54,
                'user_id' => 7,
                'type' => 'qualification_approved',
                'title' => 'Qualificação aprovada',
                'message' => 'Seu perfil agora se qualifica para pesquisas de nível superior.',
                'icon' => 'verified',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 1,
                'read_at' => '2026-01-31 15:46:49',
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 2,
                'data' => '{"new_level": "advanced"}',
                'created_at' => '2026-01-31 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            54 =>
            array (
                'id' => 55,
                'user_id' => 7,
                'type' => 'profile_update',
                'title' => 'Atualize seu perfil',
                'message' => 'Complete seu perfil para receber mais pesquisas compatíveis.',
                'icon' => 'person',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 1,
                'data' => '{"completion_percentage": "65%"}',
                'created_at' => '2026-01-29 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            55 =>
            array (
                'id' => 56,
                'user_id' => 7,
                'type' => 'weekly_summary',
                'title' => 'Resumo semanal',
                'message' => 'Esta semana você ganhou MZN 125.00 respondendo pesquisas. Continue assim!',
                'icon' => 'assessment',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 1,
                'read_at' => '2026-02-04 15:46:49',
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 1,
                'data' => '{"earnings": 125, "surveys_completed": 5}',
                'created_at' => '2026-02-04 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            56 =>
            array (
                'id' => 57,
                'user_id' => 8,
                'type' => 'survey_available',
                'title' => 'Nova pesquisa disponível',
                'message' => 'Pesquisa sobre hábitos de consumo - Ganhe MZN 30 por responder.',
                'icon' => 'assignment',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 1,
                'data' => '{"reward": 30, "survey_id": 16}',
                'created_at' => '2026-02-05 14:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            57 =>
            array (
                'id' => 58,
                'user_id' => 8,
                'type' => 'survey_available',
                'title' => 'Pesquisa compatível com seu perfil',
                'message' => 'Pesquisa sobre educação online para moradores de Maputo Província',
                'icon' => 'assignment',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 1,
                'data' => '{"reward": 25, "survey_id": 21}',
                'created_at' => '2026-02-05 11:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            58 =>
            array (
                'id' => 59,
                'user_id' => 8,
                'type' => 'bonus_received',
                'title' => 'Bônus recebido!',
                'message' => 'Você ganhou um bônus de MZN 10 por responder 5 pesquisas este mês.',
                'icon' => 'card_giftcard',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 2,
                'data' => '{"amount": 10, "reason": "fidelity"}',
                'created_at' => '2026-02-04 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            59 =>
            array (
                'id' => 60,
                'user_id' => 8,
                'type' => 'response_completed',
                'title' => 'Resposta completada',
                'message' => 'Você completou a pesquisa "Tecnologia na Educação" - MZN 25 creditado.',
                'icon' => 'done_all',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 1,
                'read_at' => '2026-02-03 15:46:49',
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 1,
                'data' => '{"amount": 25, "survey_id": 30}',
                'created_at' => '2026-02-03 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            60 =>
            array (
                'id' => 61,
                'user_id' => 8,
                'type' => 'payment_credited',
                'title' => 'Pagamento creditado',
                'message' => 'Recebeu MZN 75.00 por pesquisas respondidas.',
                'icon' => 'payments',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 1,
                'read_at' => '2026-02-02 15:46:49',
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 2,
                'data' => '{"amount": 75}',
                'created_at' => '2026-02-02 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            61 =>
            array (
                'id' => 62,
                'user_id' => 8,
                'type' => 'qualification_approved',
                'title' => 'Qualificação aprovada',
                'message' => 'Seu perfil agora se qualifica para pesquisas de nível superior.',
                'icon' => 'verified',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 1,
                'read_at' => '2026-01-31 15:46:49',
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 2,
                'data' => '{"new_level": "advanced"}',
                'created_at' => '2026-01-31 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            62 =>
            array (
                'id' => 63,
                'user_id' => 8,
                'type' => 'profile_update',
                'title' => 'Atualize seu perfil',
                'message' => 'Complete seu perfil para receber mais pesquisas compatíveis.',
                'icon' => 'person',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 1,
                'data' => '{"completion_percentage": "65%"}',
                'created_at' => '2026-01-29 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            63 =>
            array (
                'id' => 64,
                'user_id' => 8,
                'type' => 'weekly_summary',
                'title' => 'Resumo semanal',
                'message' => 'Esta semana você ganhou MZN 125.00 respondendo pesquisas. Continue assim!',
                'icon' => 'assessment',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 1,
                'read_at' => '2026-02-04 15:46:49',
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 1,
                'data' => '{"earnings": 125, "surveys_completed": 5}',
                'created_at' => '2026-02-04 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            64 =>
            array (
                'id' => 65,
                'user_id' => 9,
                'type' => 'survey_available',
                'title' => 'Nova pesquisa disponível',
                'message' => 'Pesquisa sobre hábitos de consumo - Ganhe MZN 30 por responder.',
                'icon' => 'assignment',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 1,
                'data' => '{"reward": 30, "survey_id": 18}',
                'created_at' => '2026-02-05 14:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            65 =>
            array (
                'id' => 66,
                'user_id' => 9,
                'type' => 'survey_available',
                'title' => 'Pesquisa compatível com seu perfil',
                'message' => 'Pesquisa sobre educação online para moradores de Gaza',
                'icon' => 'assignment',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 1,
                'data' => '{"reward": 25, "survey_id": 25}',
                'created_at' => '2026-02-05 11:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            66 =>
            array (
                'id' => 67,
                'user_id' => 9,
                'type' => 'bonus_received',
                'title' => 'Bônus recebido!',
                'message' => 'Você ganhou um bônus de MZN 10 por responder 5 pesquisas este mês.',
                'icon' => 'card_giftcard',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 2,
                'data' => '{"amount": 10, "reason": "fidelity"}',
                'created_at' => '2026-02-04 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            67 =>
            array (
                'id' => 68,
                'user_id' => 9,
                'type' => 'response_completed',
                'title' => 'Resposta completada',
                'message' => 'Você completou a pesquisa "Tecnologia na Educação" - MZN 25 creditado.',
                'icon' => 'done_all',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 1,
                'read_at' => '2026-02-03 15:46:49',
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 1,
                'data' => '{"amount": 25, "survey_id": 26}',
                'created_at' => '2026-02-03 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            68 =>
            array (
                'id' => 69,
                'user_id' => 9,
                'type' => 'payment_credited',
                'title' => 'Pagamento creditado',
                'message' => 'Recebeu MZN 75.00 por pesquisas respondidas.',
                'icon' => 'payments',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 1,
                'read_at' => '2026-02-02 15:46:49',
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 2,
                'data' => '{"amount": 75}',
                'created_at' => '2026-02-02 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            69 =>
            array (
                'id' => 70,
                'user_id' => 9,
                'type' => 'qualification_approved',
                'title' => 'Qualificação aprovada',
                'message' => 'Seu perfil agora se qualifica para pesquisas de nível superior.',
                'icon' => 'verified',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 1,
                'read_at' => '2026-01-31 15:46:49',
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 2,
                'data' => '{"new_level": "advanced"}',
                'created_at' => '2026-01-31 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            70 =>
            array (
                'id' => 71,
                'user_id' => 9,
                'type' => 'profile_update',
                'title' => 'Atualize seu perfil',
                'message' => 'Complete seu perfil para receber mais pesquisas compatíveis.',
                'icon' => 'person',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 1,
                'data' => '{"completion_percentage": "65%"}',
                'created_at' => '2026-01-29 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            71 =>
            array (
                'id' => 72,
                'user_id' => 9,
                'type' => 'weekly_summary',
                'title' => 'Resumo semanal',
                'message' => 'Esta semana você ganhou MZN 125.00 respondendo pesquisas. Continue assim!',
                'icon' => 'assessment',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 1,
                'read_at' => '2026-02-04 15:46:49',
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 1,
                'data' => '{"earnings": 125, "surveys_completed": 5}',
                'created_at' => '2026-02-04 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            72 =>
            array (
                'id' => 73,
                'user_id' => 10,
                'type' => 'survey_available',
                'title' => 'Nova pesquisa disponível',
                'message' => 'Pesquisa sobre hábitos de consumo - Ganhe MZN 30 por responder.',
                'icon' => 'assignment',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 1,
                'read_at' => '2026-02-07 07:45:41',
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 1,
                'data' => '{"reward": 30, "survey_id": 20}',
                'created_at' => '2026-02-05 14:46:49',
                'updated_at' => '2026-02-07 07:45:41',
            ),
            73 =>
            array (
                'id' => 74,
                'user_id' => 10,
                'type' => 'survey_available',
                'title' => 'Pesquisa compatível com seu perfil',
                'message' => 'Pesquisa sobre educação online para moradores de Inhambane',
                'icon' => 'assignment',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 1,
                'read_at' => '2026-02-07 07:45:41',
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 1,
                'data' => '{"reward": 25, "survey_id": 24}',
                'created_at' => '2026-02-05 11:46:49',
                'updated_at' => '2026-02-07 07:45:41',
            ),
            74 =>
            array (
                'id' => 75,
                'user_id' => 10,
                'type' => 'bonus_received',
                'title' => 'Bônus recebido!',
                'message' => 'Você ganhou um bônus de MZN 10 por responder 5 pesquisas este mês.',
                'icon' => 'card_giftcard',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 1,
                'read_at' => '2026-02-07 07:45:41',
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 2,
                'data' => '{"amount": 10, "reason": "fidelity"}',
                'created_at' => '2026-02-04 15:46:49',
                'updated_at' => '2026-02-07 07:45:41',
            ),
            75 =>
            array (
                'id' => 76,
                'user_id' => 10,
                'type' => 'response_completed',
                'title' => 'Resposta completada',
                'message' => 'Você completou a pesquisa "Tecnologia na Educação" - MZN 25 creditado.',
                'icon' => 'done_all',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 1,
                'read_at' => '2026-02-03 15:46:49',
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 1,
                'data' => '{"amount": 25, "survey_id": 27}',
                'created_at' => '2026-02-03 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            76 =>
            array (
                'id' => 77,
                'user_id' => 10,
                'type' => 'payment_credited',
                'title' => 'Pagamento creditado',
                'message' => 'Recebeu MZN 75.00 por pesquisas respondidas.',
                'icon' => 'payments',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 1,
                'read_at' => '2026-02-02 15:46:49',
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 2,
                'data' => '{"amount": 75}',
                'created_at' => '2026-02-02 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            77 =>
            array (
                'id' => 78,
                'user_id' => 10,
                'type' => 'qualification_approved',
                'title' => 'Qualificação aprovada',
                'message' => 'Seu perfil agora se qualifica para pesquisas de nível superior.',
                'icon' => 'verified',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 1,
                'read_at' => '2026-01-31 15:46:49',
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 2,
                'data' => '{"new_level": "advanced"}',
                'created_at' => '2026-01-31 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            78 =>
            array (
                'id' => 79,
                'user_id' => 10,
                'type' => 'profile_update',
                'title' => 'Atualize seu perfil',
                'message' => 'Complete seu perfil para receber mais pesquisas compatíveis.',
                'icon' => 'person',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 1,
                'read_at' => '2026-02-07 07:45:41',
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 1,
                'data' => '{"completion_percentage": "65%"}',
                'created_at' => '2026-01-29 15:46:49',
                'updated_at' => '2026-02-07 07:45:41',
            ),
            79 =>
            array (
                'id' => 80,
                'user_id' => 10,
                'type' => 'weekly_summary',
                'title' => 'Resumo semanal',
                'message' => 'Esta semana você ganhou MZN 125.00 respondendo pesquisas. Continue assim!',
                'icon' => 'assessment',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 1,
                'read_at' => '2026-02-04 15:46:49',
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 1,
                'data' => '{"earnings": 125, "surveys_completed": 5}',
                'created_at' => '2026-02-04 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            80 =>
            array (
                'id' => 81,
                'user_id' => 11,
                'type' => 'survey_available',
                'title' => 'Nova pesquisa disponível',
                'message' => 'Pesquisa sobre hábitos de consumo - Ganhe MZN 30 por responder.',
                'icon' => 'assignment',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 1,
                'data' => '{"reward": 30, "survey_id": 17}',
                'created_at' => '2026-02-05 14:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            81 =>
            array (
                'id' => 82,
                'user_id' => 11,
                'type' => 'survey_available',
                'title' => 'Pesquisa compatível com seu perfil',
                'message' => 'Pesquisa sobre educação online para moradores de Sofala',
                'icon' => 'assignment',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 1,
                'data' => '{"reward": 25, "survey_id": 21}',
                'created_at' => '2026-02-05 11:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            82 =>
            array (
                'id' => 83,
                'user_id' => 11,
                'type' => 'bonus_received',
                'title' => 'Bônus recebido!',
                'message' => 'Você ganhou um bônus de MZN 10 por responder 5 pesquisas este mês.',
                'icon' => 'card_giftcard',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 2,
                'data' => '{"amount": 10, "reason": "fidelity"}',
                'created_at' => '2026-02-04 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            83 =>
            array (
                'id' => 84,
                'user_id' => 11,
                'type' => 'response_completed',
                'title' => 'Resposta completada',
                'message' => 'Você completou a pesquisa "Tecnologia na Educação" - MZN 25 creditado.',
                'icon' => 'done_all',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 1,
                'read_at' => '2026-02-03 15:46:49',
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 1,
                'data' => '{"amount": 25, "survey_id": 29}',
                'created_at' => '2026-02-03 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            84 =>
            array (
                'id' => 85,
                'user_id' => 11,
                'type' => 'payment_credited',
                'title' => 'Pagamento creditado',
                'message' => 'Recebeu MZN 75.00 por pesquisas respondidas.',
                'icon' => 'payments',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 1,
                'read_at' => '2026-02-02 15:46:49',
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 2,
                'data' => '{"amount": 75}',
                'created_at' => '2026-02-02 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            85 =>
            array (
                'id' => 86,
                'user_id' => 11,
                'type' => 'qualification_approved',
                'title' => 'Qualificação aprovada',
                'message' => 'Seu perfil agora se qualifica para pesquisas de nível superior.',
                'icon' => 'verified',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 1,
                'read_at' => '2026-01-31 15:46:49',
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 2,
                'data' => '{"new_level": "advanced"}',
                'created_at' => '2026-01-31 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            86 =>
            array (
                'id' => 87,
                'user_id' => 11,
                'type' => 'profile_update',
                'title' => 'Atualize seu perfil',
                'message' => 'Complete seu perfil para receber mais pesquisas compatíveis.',
                'icon' => 'person',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 1,
                'data' => '{"completion_percentage": "65%"}',
                'created_at' => '2026-01-29 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            87 =>
            array (
                'id' => 88,
                'user_id' => 11,
                'type' => 'weekly_summary',
                'title' => 'Resumo semanal',
                'message' => 'Esta semana você ganhou MZN 125.00 respondendo pesquisas. Continue assim!',
                'icon' => 'assessment',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 1,
                'read_at' => '2026-02-04 15:46:49',
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 1,
                'data' => '{"earnings": 125, "surveys_completed": 5}',
                'created_at' => '2026-02-04 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            88 =>
            array (
                'id' => 89,
                'user_id' => 12,
                'type' => 'survey_available',
                'title' => 'Nova pesquisa disponível',
                'message' => 'Pesquisa sobre hábitos de consumo - Ganhe MZN 30 por responder.',
                'icon' => 'assignment',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 1,
                'data' => '{"reward": 30, "survey_id": 16}',
                'created_at' => '2026-02-05 14:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            89 =>
            array (
                'id' => 90,
                'user_id' => 12,
                'type' => 'survey_available',
                'title' => 'Pesquisa compatível com seu perfil',
                'message' => 'Pesquisa sobre educação online para moradores de Manica',
                'icon' => 'assignment',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 1,
                'data' => '{"reward": 25, "survey_id": 22}',
                'created_at' => '2026-02-05 11:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            90 =>
            array (
                'id' => 91,
                'user_id' => 12,
                'type' => 'bonus_received',
                'title' => 'Bônus recebido!',
                'message' => 'Você ganhou um bônus de MZN 10 por responder 5 pesquisas este mês.',
                'icon' => 'card_giftcard',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 2,
                'data' => '{"amount": 10, "reason": "fidelity"}',
                'created_at' => '2026-02-04 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            91 =>
            array (
                'id' => 92,
                'user_id' => 12,
                'type' => 'response_completed',
                'title' => 'Resposta completada',
                'message' => 'Você completou a pesquisa "Tecnologia na Educação" - MZN 25 creditado.',
                'icon' => 'done_all',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 1,
                'read_at' => '2026-02-03 15:46:49',
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 1,
                'data' => '{"amount": 25, "survey_id": 26}',
                'created_at' => '2026-02-03 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            92 =>
            array (
                'id' => 93,
                'user_id' => 12,
                'type' => 'payment_credited',
                'title' => 'Pagamento creditado',
                'message' => 'Recebeu MZN 75.00 por pesquisas respondidas.',
                'icon' => 'payments',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 1,
                'read_at' => '2026-02-02 15:46:49',
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 2,
                'data' => '{"amount": 75}',
                'created_at' => '2026-02-02 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            93 =>
            array (
                'id' => 94,
                'user_id' => 12,
                'type' => 'qualification_approved',
                'title' => 'Qualificação aprovada',
                'message' => 'Seu perfil agora se qualifica para pesquisas de nível superior.',
                'icon' => 'verified',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 1,
                'read_at' => '2026-01-31 15:46:49',
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 2,
                'data' => '{"new_level": "advanced"}',
                'created_at' => '2026-01-31 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            94 =>
            array (
                'id' => 95,
                'user_id' => 12,
                'type' => 'profile_update',
                'title' => 'Atualize seu perfil',
                'message' => 'Complete seu perfil para receber mais pesquisas compatíveis.',
                'icon' => 'person',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 1,
                'data' => '{"completion_percentage": "65%"}',
                'created_at' => '2026-01-29 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            95 =>
            array (
                'id' => 96,
                'user_id' => 12,
                'type' => 'weekly_summary',
                'title' => 'Resumo semanal',
                'message' => 'Esta semana você ganhou MZN 125.00 respondendo pesquisas. Continue assim!',
                'icon' => 'assessment',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 1,
                'read_at' => '2026-02-04 15:46:49',
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 1,
                'data' => '{"earnings": 125, "surveys_completed": 5}',
                'created_at' => '2026-02-04 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            96 =>
            array (
                'id' => 97,
                'user_id' => 14,
                'type' => 'survey_available',
                'title' => 'Nova pesquisa disponível',
                'message' => 'Pesquisa sobre hábitos de consumo - Ganhe MZN 30 por responder.',
                'icon' => 'assignment',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 1,
                'data' => '{"reward": 30, "survey_id": 16}',
                'created_at' => '2026-02-05 14:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            97 =>
            array (
                'id' => 98,
                'user_id' => 14,
                'type' => 'survey_available',
                'title' => 'Pesquisa compatível com seu perfil',
                'message' => 'Pesquisa sobre educação online para moradores de Zambézia',
                'icon' => 'assignment',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 1,
                'data' => '{"reward": 25, "survey_id": 25}',
                'created_at' => '2026-02-05 11:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            98 =>
            array (
                'id' => 99,
                'user_id' => 14,
                'type' => 'bonus_received',
                'title' => 'Bônus recebido!',
                'message' => 'Você ganhou um bônus de MZN 10 por responder 5 pesquisas este mês.',
                'icon' => 'card_giftcard',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 2,
                'data' => '{"amount": 10, "reason": "fidelity"}',
                'created_at' => '2026-02-04 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            99 =>
            array (
                'id' => 100,
                'user_id' => 14,
                'type' => 'response_completed',
                'title' => 'Resposta completada',
                'message' => 'Você completou a pesquisa "Tecnologia na Educação" - MZN 25 creditado.',
                'icon' => 'done_all',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 1,
                'read_at' => '2026-02-03 15:46:49',
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 1,
                'data' => '{"amount": 25, "survey_id": 28}',
                'created_at' => '2026-02-03 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            100 =>
            array (
                'id' => 101,
                'user_id' => 14,
                'type' => 'payment_credited',
                'title' => 'Pagamento creditado',
                'message' => 'Recebeu MZN 75.00 por pesquisas respondidas.',
                'icon' => 'payments',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 1,
                'read_at' => '2026-02-02 15:46:49',
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 2,
                'data' => '{"amount": 75}',
                'created_at' => '2026-02-02 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            101 =>
            array (
                'id' => 102,
                'user_id' => 14,
                'type' => 'qualification_approved',
                'title' => 'Qualificação aprovada',
                'message' => 'Seu perfil agora se qualifica para pesquisas de nível superior.',
                'icon' => 'verified',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 1,
                'read_at' => '2026-01-31 15:46:49',
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 2,
                'data' => '{"new_level": "advanced"}',
                'created_at' => '2026-01-31 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            102 =>
            array (
                'id' => 103,
                'user_id' => 14,
                'type' => 'profile_update',
                'title' => 'Atualize seu perfil',
                'message' => 'Complete seu perfil para receber mais pesquisas compatíveis.',
                'icon' => 'person',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 1,
                'data' => '{"completion_percentage": "65%"}',
                'created_at' => '2026-01-29 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            103 =>
            array (
                'id' => 104,
                'user_id' => 14,
                'type' => 'weekly_summary',
                'title' => 'Resumo semanal',
                'message' => 'Esta semana você ganhou MZN 125.00 respondendo pesquisas. Continue assim!',
                'icon' => 'assessment',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 1,
                'read_at' => '2026-02-04 15:46:49',
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 1,
                'data' => '{"earnings": 125, "surveys_completed": 5}',
                'created_at' => '2026-02-04 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            104 =>
            array (
                'id' => 105,
                'user_id' => 15,
                'type' => 'survey_available',
                'title' => 'Nova pesquisa disponível',
                'message' => 'Pesquisa sobre hábitos de consumo - Ganhe MZN 30 por responder.',
                'icon' => 'assignment',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 1,
                'data' => '{"reward": 30, "survey_id": 17}',
                'created_at' => '2026-02-05 14:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            105 =>
            array (
                'id' => 106,
                'user_id' => 15,
                'type' => 'survey_available',
                'title' => 'Pesquisa compatível com seu perfil',
                'message' => 'Pesquisa sobre educação online para moradores de Nampula',
                'icon' => 'assignment',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 1,
                'data' => '{"reward": 25, "survey_id": 22}',
                'created_at' => '2026-02-05 11:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            106 =>
            array (
                'id' => 107,
                'user_id' => 15,
                'type' => 'bonus_received',
                'title' => 'Bônus recebido!',
                'message' => 'Você ganhou um bônus de MZN 10 por responder 5 pesquisas este mês.',
                'icon' => 'card_giftcard',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 2,
                'data' => '{"amount": 10, "reason": "fidelity"}',
                'created_at' => '2026-02-04 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            107 =>
            array (
                'id' => 108,
                'user_id' => 15,
                'type' => 'response_completed',
                'title' => 'Resposta completada',
                'message' => 'Você completou a pesquisa "Tecnologia na Educação" - MZN 25 creditado.',
                'icon' => 'done_all',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 1,
                'read_at' => '2026-02-03 15:46:49',
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 1,
                'data' => '{"amount": 25, "survey_id": 28}',
                'created_at' => '2026-02-03 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            108 =>
            array (
                'id' => 109,
                'user_id' => 15,
                'type' => 'payment_credited',
                'title' => 'Pagamento creditado',
                'message' => 'Recebeu MZN 75.00 por pesquisas respondidas.',
                'icon' => 'payments',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 1,
                'read_at' => '2026-02-02 15:46:49',
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 2,
                'data' => '{"amount": 75}',
                'created_at' => '2026-02-02 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            109 =>
            array (
                'id' => 110,
                'user_id' => 15,
                'type' => 'qualification_approved',
                'title' => 'Qualificação aprovada',
                'message' => 'Seu perfil agora se qualifica para pesquisas de nível superior.',
                'icon' => 'verified',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 1,
                'read_at' => '2026-01-31 15:46:49',
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 2,
                'data' => '{"new_level": "advanced"}',
                'created_at' => '2026-01-31 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            110 =>
            array (
                'id' => 111,
                'user_id' => 15,
                'type' => 'profile_update',
                'title' => 'Atualize seu perfil',
                'message' => 'Complete seu perfil para receber mais pesquisas compatíveis.',
                'icon' => 'person',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 1,
                'data' => '{"completion_percentage": "65%"}',
                'created_at' => '2026-01-29 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            111 =>
            array (
                'id' => 112,
                'user_id' => 15,
                'type' => 'weekly_summary',
                'title' => 'Resumo semanal',
                'message' => 'Esta semana você ganhou MZN 125.00 respondendo pesquisas. Continue assim!',
                'icon' => 'assessment',
                'action_url' => '/surveys',
                'action_label' => 'Ver pesquisas',
                'is_read' => 1,
                'read_at' => '2026-02-04 15:46:49',
                'expires_at' => '2026-02-20 15:46:49',
                'priority' => 1,
                'data' => '{"earnings": 125, "surveys_completed": 5}',
                'created_at' => '2026-02-04 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            112 =>
            array (
                'id' => 113,
                'user_id' => 1,
                'type' => 'system_alert',
                'title' => 'Alerta do sistema',
                'message' => 'Alta atividade de respostas detectada nas últimas 24h. Verifique logs.',
                'icon' => 'warning',
                'action_url' => '/admin/dashboard',
                'action_label' => 'Administrar',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-04-06 15:46:49',
                'priority' => 3,
                'data' => '{"activity_count": 245}',
                'created_at' => '2026-02-05 14:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            113 =>
            array (
                'id' => 114,
                'user_id' => 1,
                'type' => 'new_user_registered',
                'title' => 'Novo estudante registrado',
                'message' => 'Ana Paula Macuácua registrou-se como estudante do ISCTEM.',
                'icon' => 'person_add',
                'action_url' => '/admin/dashboard',
                'action_label' => 'Administrar',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-04-06 15:46:49',
                'priority' => 2,
                'data' => '{"user_id": 6, "user_type": "student"}',
                'created_at' => '2026-02-05 12:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            114 =>
            array (
                'id' => 115,
                'user_id' => 1,
                'type' => 'survey_pending_review',
                'title' => 'Pesquisas pendentes',
                'message' => '3 pesquisas aguardando aprovação.',
                'icon' => 'pending_actions',
                'action_url' => '/admin/dashboard',
                'action_label' => 'Administrar',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-04-06 15:46:49',
                'priority' => 2,
                'data' => '{"pending_count": 3}',
                'created_at' => '2026-02-05 09:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            115 =>
            array (
                'id' => 116,
                'user_id' => 1,
                'type' => 'withdrawal_requested',
                'title' => 'Novo pedido de saque',
                'message' => 'Carlos Mondlane solicitou saque de MZN 300.00.',
                'icon' => 'request_quote',
                'action_url' => '/admin/dashboard',
                'action_label' => 'Administrar',
                'is_read' => 1,
                'read_at' => '2026-02-07 08:31:53',
                'expires_at' => '2026-04-06 15:46:49',
                'priority' => 2,
                'data' => '{"amount": 300, "user_id": 2}',
                'created_at' => '2026-02-05 03:46:49',
                'updated_at' => '2026-02-07 08:31:53',
            ),
            116 =>
            array (
                'id' => 117,
                'user_id' => 1,
                'type' => 'user_verification_pending',
                'title' => 'Verificações pendentes',
                'message' => '2 usuários aguardando verificação de documentos.',
                'icon' => 'verified_user',
                'action_url' => '/admin/dashboard',
                'action_label' => 'Administrar',
                'is_read' => 1,
                'read_at' => '2026-02-04 15:46:49',
                'expires_at' => '2026-04-06 15:46:49',
                'priority' => 1,
                'data' => '{"pending_verifications": 2}',
                'created_at' => '2026-02-04 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            117 =>
            array (
                'id' => 118,
                'user_id' => 1,
                'type' => 'batch_payment_processed',
                'title' => 'Pagamentos processados',
                'message' => 'Pagamentos em lote processados: 15 transações concluídas.',
                'icon' => 'payments',
                'action_url' => '/admin/dashboard',
                'action_label' => 'Administrar',
                'is_read' => 1,
                'read_at' => '2026-02-03 15:46:49',
                'expires_at' => '2026-04-06 15:46:49',
                'priority' => 1,
                'data' => '{"total_amount": 1250, "transactions": 15}',
                'created_at' => '2026-02-03 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            118 =>
            array (
                'id' => 119,
                'user_id' => 1,
                'type' => 'low_system_funds',
                'title' => 'Fundos do sistema baixos',
                'message' => 'Fundos do sistema: MZN 1.500 restantes. Considere recarregar.',
                'icon' => 'account_balance',
                'action_url' => '/admin/dashboard',
                'action_label' => 'Administrar',
                'is_read' => 1,
                'read_at' => '2026-02-02 15:46:49',
                'expires_at' => '2026-04-06 15:46:49',
                'priority' => 2,
                'data' => '{"balance": 1500, "threshold": 2000}',
                'created_at' => '2026-02-02 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            119 =>
            array (
                'id' => 120,
                'user_id' => 1,
                'type' => 'general_announcement',
                'title' => 'Relatório semanal disponível',
                'message' => 'Relatório semanal do sistema está disponível para consulta.',
                'icon' => 'assessment',
                'action_url' => '/admin/dashboard',
                'action_label' => 'Administrar',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-04-06 15:46:49',
                'priority' => 1,
                'data' => '{"period": "semanal", "report_id": 1}',
                'created_at' => '2026-02-04 15:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            120 =>
            array (
                'id' => 121,
                'user_id' => 1,
                'type' => 'high_activity',
                'title' => 'Alta atividade detectada',
                'message' => 'Pico de acessos detectado: 1.234 usuários ativos nas últimas 2h.',
                'icon' => 'trending_up',
                'action_url' => '/admin/dashboard',
                'action_label' => 'Administrar',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-04-06 15:46:49',
                'priority' => 2,
                'data' => '{"time_period": "2h", "active_users": 1234}',
                'created_at' => '2026-02-05 13:46:49',
                'updated_at' => '2026-02-05 15:46:49',
            ),
            121 =>
            array (
                'id' => 122,
                'user_id' => 16,
                'type' => 'survey_response',
                'title' => 'Progresso da pesquisa',
                'message' => 'Sua pesquisa sobre metodologias de ensino já tem 120 respostas.',
                'icon' => 'assignment_turned_in',
                'action_url' => '/research/dashboard',
                'action_label' => 'Ver pesquisa',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-03-22 15:46:50',
                'priority' => 1,
                'data' => '{"responses": 120, "survey_id": 31}',
                'created_at' => '2026-02-05 11:46:50',
                'updated_at' => '2026-02-05 15:46:50',
            ),
            122 =>
            array (
                'id' => 123,
                'user_id' => 16,
                'type' => 'deadline_alert',
                'title' => 'Prazo importante',
                'message' => 'Último dia para coletar dados da sua pesquisa de mestrado.',
                'icon' => 'event',
                'action_url' => '/research/dashboard',
                'action_label' => 'Ver pesquisa',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-03-22 15:46:50',
                'priority' => 3,
                'data' => '{"deadline_date": "2026-02-06"}',
                'created_at' => '2026-02-04 15:46:50',
                'updated_at' => '2026-02-05 15:46:50',
            ),
            123 =>
            array (
                'id' => 124,
                'user_id' => 16,
                'type' => 'research_reminder',
                'title' => 'Lembrete de análise',
                'message' => 'Lembre-se de analisar os dados coletados esta semana.',
                'icon' => 'analytics',
                'action_url' => '/research/dashboard',
                'action_label' => 'Ver pesquisa',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-03-22 15:46:50',
                'priority' => 2,
                'data' => '{"reminder_type": "data_analysis"}',
                'created_at' => '2026-02-03 15:46:50',
                'updated_at' => '2026-02-05 15:46:50',
            ),
            124 =>
            array (
                'id' => 125,
                'user_id' => 16,
                'type' => 'survey_approved',
                'title' => 'Pesquisa aprovada pelo comitê',
                'message' => 'Sua pesquisa foi aprovada pelo comitê de ética.',
                'icon' => 'verified',
                'action_url' => '/research/dashboard',
                'action_label' => 'Ver pesquisa',
                'is_read' => 1,
                'read_at' => '2026-02-02 15:46:50',
                'expires_at' => '2026-03-22 15:46:50',
                'priority' => 2,
                'data' => '{"committee": "Comitê de Ética em Pesquisa"}',
                'created_at' => '2026-02-02 15:46:50',
                'updated_at' => '2026-02-05 15:46:50',
            ),
            125 =>
            array (
                'id' => 126,
                'user_id' => 16,
                'type' => 'general_announcement',
                'title' => 'Comentários dos participantes',
                'message' => 'Os participantes deixaram comentários sobre sua pesquisa.',
                'icon' => 'forum',
                'action_url' => '/research/dashboard',
                'action_label' => 'Ver pesquisa',
                'is_read' => 1,
                'read_at' => '2026-02-01 15:46:50',
                'expires_at' => '2026-03-22 15:46:50',
                'priority' => 1,
                'data' => '{"feedback_count": 8}',
                'created_at' => '2026-02-01 15:46:50',
                'updated_at' => '2026-02-05 15:46:50',
            ),
            126 =>
            array (
                'id' => 127,
                'user_id' => 16,
                'type' => 'general_announcement',
                'title' => 'Novo recurso disponível',
                'message' => 'Curso: "Análise de Dados Qualitativos" disponível na plataforma.',
                'icon' => 'school',
                'action_url' => '/research/dashboard',
                'action_label' => 'Ver pesquisa',
                'is_read' => 0,
                'read_at' => NULL,
                'expires_at' => '2026-03-22 15:46:50',
                'priority' => 1,
                'data' => '{"course_id": 1, "course_title": "Análise de Dados Qualitativos"}',
                'created_at' => '2026-01-31 15:46:50',
                'updated_at' => '2026-02-05 15:46:50',
            ),
        ));


    }
}
