<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ParticipantStatsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('participant_stats')->delete();
        
        \DB::table('participant_stats')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_id' => 7,
                'birth_date' => '1985-04-12',
                'gender' => 'masculino',
                'province' => 'Maputo Cidade',
                'bi_number' => '678901234567F',
                'mpesa_number' => '+258846667788',
                'occupation' => 'Engenheiro Civil',
                'education_level' => 'Licenciatura',
                'research_interests' => '"[\\"tecnologia\\",\\"infraestrutura\\",\\"desenvolvimento_urbano\\"]"',
            'participation_frequency' => 'Regularmente (várias vezes por semana)',
                'consent_data_collection' => 1,
                'sms_notifications' => 0,
                'total_surveys_completed' => 3,
                'total_earnings' => '325.75',
                'last_survey_date' => '2026-01-29 21:35:01',
                'metadata' => NULL,
                'created_at' => '2026-02-03 21:35:01',
                'updated_at' => '2026-02-03 21:35:01',
            ),
            1 => 
            array (
                'id' => 2,
                'user_id' => 8,
                'birth_date' => '1990-08-25',
                'gender' => 'feminino',
                'province' => 'Maputo Província',
                'bi_number' => '789012345678G',
                'mpesa_number' => '+258847778899',
                'occupation' => 'Professora',
                'education_level' => 'Pós-graduação/Mestrado',
                'research_interests' => '"[\\"educacao\\",\\"formacao_continua\\",\\"tecnologia_educativa\\"]"',
            'participation_frequency' => 'Frequentemente (1-2 vezes por semana)',
                'consent_data_collection' => 1,
                'sms_notifications' => 0,
                'total_surveys_completed' => 19,
                'total_earnings' => '480.50',
                'last_survey_date' => '2025-12-05 21:35:01',
                'metadata' => NULL,
                'created_at' => '2026-02-03 21:35:01',
                'updated_at' => '2026-02-03 21:35:01',
            ),
            2 => 
            array (
                'id' => 3,
                'user_id' => 9,
                'birth_date' => '1988-12-18',
                'gender' => 'masculino',
                'province' => 'Gaza',
                'bi_number' => '890123456789H',
                'mpesa_number' => '+258848889900',
                'occupation' => 'Empresário',
                'education_level' => 'Ensino Superior Incompleto',
                'research_interests' => '"[\\"economia\\",\\"empreendedorismo\\",\\"gestao\\"]"',
            'participation_frequency' => 'Ocasionalmente (1-2 vezes por mês)',
                'consent_data_collection' => 1,
                'sms_notifications' => 0,
                'total_surveys_completed' => 2,
                'total_earnings' => '195.00',
                'last_survey_date' => '2026-01-30 21:35:01',
                'metadata' => NULL,
                'created_at' => '2026-02-03 21:35:01',
                'updated_at' => '2026-02-03 21:35:01',
            ),
            3 => 
            array (
                'id' => 4,
                'user_id' => 10,
                'birth_date' => '1992-03-30',
                'gender' => 'feminino',
                'province' => 'Inhambane',
                'bi_number' => '901234567890I',
                'mpesa_number' => '+258849990011',
                'occupation' => 'Médica',
                'education_level' => 'Licenciatura',
                'research_interests' => '"[\\"saude\\",\\"medicina_preventiva\\",\\"nutricao\\"]"',
            'participation_frequency' => 'Regularmente (várias vezes por semana)',
                'consent_data_collection' => 1,
                'sms_notifications' => 0,
                'total_surveys_completed' => 14,
                'total_earnings' => '620.25',
                'last_survey_date' => '2025-12-16 21:35:01',
                'metadata' => NULL,
                'created_at' => '2026-02-03 21:35:01',
                'updated_at' => '2026-02-03 21:35:01',
            ),
            4 => 
            array (
                'id' => 5,
                'user_id' => 11,
                'birth_date' => '1975-06-22',
                'gender' => 'masculino',
                'province' => 'Sofala',
                'bi_number' => '012345678901J',
                'mpesa_number' => '+258840011122',
                'occupation' => 'Funcionário Público',
                'education_level' => 'Curso Técnico',
                'research_interests' => '"[\\"administracao_publica\\",\\"politica\\",\\"gestao_publica\\"]"',
            'participation_frequency' => 'Regularmente (várias vezes por semana)',
                'consent_data_collection' => 1,
                'sms_notifications' => 0,
                'total_surveys_completed' => 15,
                'total_earnings' => '275.50',
                'last_survey_date' => '2025-12-20 21:35:01',
                'metadata' => NULL,
                'created_at' => '2026-02-03 21:35:01',
                'updated_at' => '2026-02-03 21:35:01',
            ),
            5 => 
            array (
                'id' => 6,
                'user_id' => 12,
                'birth_date' => '1995-09-14',
                'gender' => 'feminino',
                'province' => 'Manica',
                'bi_number' => '112345678901K',
                'mpesa_number' => '+258841122233',
                'occupation' => 'Estudante Universitário',
                'education_level' => 'Ensino Superior Incompleto',
                'research_interests' => '"[\\"sociologia\\",\\"desenvolvimento_comunitario\\",\\"genero\\"]"',
            'participation_frequency' => 'Frequentemente (1-2 vezes por semana)',
                'consent_data_collection' => 1,
                'sms_notifications' => 0,
                'total_surveys_completed' => 3,
                'total_earnings' => '150.00',
                'last_survey_date' => '2025-12-12 21:35:01',
                'metadata' => NULL,
                'created_at' => '2026-02-03 21:35:01',
                'updated_at' => '2026-02-03 21:35:01',
            ),
            6 => 
            array (
                'id' => 7,
                'user_id' => 13,
                'birth_date' => '1998-01-27',
                'gender' => 'masculino',
                'province' => 'Tete',
                'bi_number' => '212345678901L',
                'mpesa_number' => '+258842233344',
                'occupation' => 'Agricultor',
            'education_level' => 'Ensino Secundário (até 10ª classe)',
                'research_interests' => '"[\\"agricultura\\",\\"meio_ambiente\\",\\"desenvolvimento_rural\\"]"',
            'participation_frequency' => 'Frequentemente (1-2 vezes por semana)',
                'consent_data_collection' => 1,
                'sms_notifications' => 0,
                'total_surveys_completed' => 18,
                'total_earnings' => '0.00',
                'last_survey_date' => '2026-01-12 21:35:01',
                'metadata' => NULL,
                'created_at' => '2026-02-03 21:35:01',
                'updated_at' => '2026-02-03 21:35:01',
            ),
            7 => 
            array (
                'id' => 8,
                'user_id' => 14,
                'birth_date' => '1987-11-19',
                'gender' => 'feminino',
                'province' => 'Zambézia',
                'bi_number' => '312345678901M',
                'mpesa_number' => '+258843344455',
                'occupation' => 'Enfermeira',
                'education_level' => 'Curso Técnico',
                'research_interests' => '"[\\"saude\\",\\"enfermagem\\",\\"cuidados_paliativos\\"]"',
            'participation_frequency' => 'Regularmente (várias vezes por semana)',
                'consent_data_collection' => 1,
                'sms_notifications' => 0,
                'total_surveys_completed' => 18,
                'total_earnings' => '385.75',
                'last_survey_date' => '2026-01-11 21:35:01',
                'metadata' => NULL,
                'created_at' => '2026-02-03 21:35:01',
                'updated_at' => '2026-02-03 21:35:01',
            ),
            8 => 
            array (
                'id' => 9,
                'user_id' => 15,
                'birth_date' => '1982-07-05',
                'gender' => 'masculino',
                'province' => 'Nampula',
                'bi_number' => '412345678901N',
                'mpesa_number' => '+258844455566',
                'occupation' => 'Comerciante',
            'education_level' => 'Ensino Médio (12ª classe)',
                'research_interests' => '"[\\"economia\\",\\"comercio\\",\\"gestao_financeira\\"]"',
            'participation_frequency' => 'Ocasionalmente (1-2 vezes por mês)',
                'consent_data_collection' => 1,
                'sms_notifications' => 0,
                'total_surveys_completed' => 12,
                'total_earnings' => '225.00',
                'last_survey_date' => '2025-11-30 21:35:01',
                'metadata' => NULL,
                'created_at' => '2026-02-03 21:35:01',
                'updated_at' => '2026-02-03 21:35:01',
            ),
            9 => 
            array (
                'id' => 10,
                'user_id' => 16,
                'birth_date' => '1993-10-15',
                'gender' => 'feminino',
                'province' => 'Cabo Delgado',
                'bi_number' => '512345678901O',
                'mpesa_number' => '+258845566677',
            'occupation' => 'Desempregado(a)',
                'education_level' => 'Ensino Superior Incompleto',
                'research_interests' => '"[\\"desenvolvimento_social\\",\\"emprego\\",\\"qualificacao_profissional\\"]"',
            'participation_frequency' => 'Ocasionalmente (1-2 vezes por mês)',
                'consent_data_collection' => 1,
                'sms_notifications' => 0,
                'total_surveys_completed' => 15,
                'total_earnings' => '0.00',
                'last_survey_date' => '2026-01-28 21:35:02',
                'metadata' => NULL,
                'created_at' => '2026-02-03 21:35:02',
                'updated_at' => '2026-02-03 21:35:02',
            ),
        ));
        
        
    }
}