<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class SurveyResponsesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('survey_responses')->delete();
        
        \DB::table('survey_responses')->insert(array (
            0 => 
            array (
                'id' => 106,
                'survey_id' => 1,
                'user_id' => 10,
                'answers' => '[3, null, null, null, null]',
                'feedback' => NULL,
                'status' => 'in_progress',
                'started_at' => '2026-02-13 06:23:56',
                'completed_at' => NULL,
                'completion_time' => 120,
                'time_spent' => NULL,
                'quality_score' => NULL,
                'rating' => NULL,
                'device_type' => 'desktop',
                'browser' => 'Chrome',
                'browser_version' => NULL,
                'os' => NULL,
                'os_version' => NULL,
                'ip_address' => '127.0.0.1',
                'country' => NULL,
                'province' => NULL,
                'city' => NULL,
                'is_paid' => 0,
                'payment_amount' => '35.00',
                'payment_date' => NULL,
                'payment_method' => NULL,
                'payment_reference' => NULL,
                'metadata' => NULL,
                'created_at' => '2026-02-13 06:23:56',
                'updated_at' => '2026-02-13 06:26:03',
            ),
            1 => 
            array (
                'id' => 107,
                'survey_id' => 15,
                'user_id' => 15,
                'answers' => '[3, ["cloud", "ia", "iot", "blockchain"], null, 3, null, null]',
                'feedback' => NULL,
                'status' => 'in_progress',
                'started_at' => '2026-02-13 09:03:43',
                'completed_at' => NULL,
                'completion_time' => 360,
                'time_spent' => NULL,
                'quality_score' => NULL,
                'rating' => NULL,
                'device_type' => 'desktop',
                'browser' => 'Chrome',
                'browser_version' => NULL,
                'os' => NULL,
                'os_version' => NULL,
                'ip_address' => '127.0.0.1',
                'country' => NULL,
                'province' => NULL,
                'city' => NULL,
                'is_paid' => 0,
                'payment_amount' => '75.00',
                'payment_date' => NULL,
                'payment_method' => NULL,
                'payment_reference' => NULL,
                'metadata' => NULL,
                'created_at' => '2026-02-13 09:03:43',
                'updated_at' => '2026-02-13 09:14:58',
            ),
            2 => 
            array (
                'id' => 108,
                'survey_id' => 1,
                'user_id' => 15,
                'answers' => '[2, 2, ["price", "quality", "brand", "promotions"], 3, "jksbdkjbsjk"]',
                'feedback' => NULL,
                'status' => 'completed',
                'started_at' => '2026-02-13 09:53:40',
                'completed_at' => '2026-02-13 09:54:16',
                'completion_time' => 32,
                'time_spent' => NULL,
                'quality_score' => NULL,
                'rating' => NULL,
                'device_type' => 'mobile',
                'browser' => 'Safari',
                'browser_version' => NULL,
                'os' => NULL,
                'os_version' => NULL,
                'ip_address' => '127.0.0.1',
                'country' => NULL,
                'province' => NULL,
                'city' => NULL,
                'is_paid' => 1,
                'payment_amount' => '35.00',
                'payment_date' => NULL,
                'payment_method' => NULL,
                'payment_reference' => NULL,
                'metadata' => NULL,
                'created_at' => '2026-02-13 09:53:40',
                'updated_at' => '2026-02-13 09:54:16',
            ),
            3 => 
            array (
                'id' => 109,
                'survey_id' => 2,
                'user_id' => 15,
                'answers' => '[null, null, null, null, null, null]',
                'feedback' => NULL,
                'status' => 'in_progress',
                'started_at' => '2026-02-13 09:54:25',
                'completed_at' => NULL,
                'completion_time' => 390,
                'time_spent' => NULL,
                'quality_score' => NULL,
                'rating' => NULL,
                'device_type' => 'mobile',
                'browser' => 'Safari',
                'browser_version' => NULL,
                'os' => NULL,
                'os_version' => NULL,
                'ip_address' => '127.0.0.1',
                'country' => NULL,
                'province' => NULL,
                'city' => NULL,
                'is_paid' => 0,
                'payment_amount' => '45.00',
                'payment_date' => NULL,
                'payment_method' => NULL,
                'payment_reference' => NULL,
                'metadata' => NULL,
                'created_at' => '2026-02-13 09:54:25',
                'updated_at' => '2026-02-13 10:16:46',
            ),
            4 => 
            array (
                'id' => 110,
                'survey_id' => 15,
                'user_id' => 10,
                'answers' => '[3, null, null, 3, null, 3]',
                'feedback' => NULL,
                'status' => 'in_progress',
                'started_at' => '2026-02-13 10:22:07',
                'completed_at' => NULL,
                'completion_time' => 540,
                'time_spent' => NULL,
                'quality_score' => NULL,
                'rating' => NULL,
                'device_type' => 'desktop',
                'browser' => 'Chrome',
                'browser_version' => NULL,
                'os' => NULL,
                'os_version' => NULL,
                'ip_address' => '127.0.0.1',
                'country' => NULL,
                'province' => NULL,
                'city' => NULL,
                'is_paid' => 0,
                'payment_amount' => '75.00',
                'payment_date' => NULL,
                'payment_method' => NULL,
                'payment_reference' => NULL,
                'metadata' => NULL,
                'created_at' => '2026-02-13 10:22:07',
                'updated_at' => '2026-02-13 10:50:16',
            ),
            5 => 
            array (
                'id' => 111,
                'survey_id' => 2,
                'user_id' => 10,
                'answers' => NULL,
                'feedback' => NULL,
                'status' => 'in_progress',
                'started_at' => '2026-02-13 11:35:30',
                'completed_at' => NULL,
                'completion_time' => NULL,
                'time_spent' => NULL,
                'quality_score' => NULL,
                'rating' => NULL,
                'device_type' => 'desktop',
                'browser' => 'Chrome',
                'browser_version' => NULL,
                'os' => NULL,
                'os_version' => NULL,
                'ip_address' => '127.0.0.1',
                'country' => NULL,
                'province' => NULL,
                'city' => NULL,
                'is_paid' => 0,
                'payment_amount' => '45.00',
                'payment_date' => NULL,
                'payment_method' => NULL,
                'payment_reference' => NULL,
                'metadata' => NULL,
                'created_at' => '2026-02-13 11:35:30',
                'updated_at' => '2026-02-13 11:35:30',
            ),
            6 => 
            array (
                'id' => 112,
                'survey_id' => 16,
                'user_id' => 10,
                'answers' => '[null, null, null, null, null, null]',
                'feedback' => NULL,
                'status' => 'in_progress',
                'started_at' => '2026-02-13 11:37:34',
                'completed_at' => NULL,
                'completion_time' => 990,
                'time_spent' => NULL,
                'quality_score' => NULL,
                'rating' => NULL,
                'device_type' => 'desktop',
                'browser' => 'Chrome',
                'browser_version' => NULL,
                'os' => NULL,
                'os_version' => NULL,
                'ip_address' => '127.0.0.1',
                'country' => NULL,
                'province' => NULL,
                'city' => NULL,
                'is_paid' => 0,
                'payment_amount' => '60.00',
                'payment_date' => NULL,
                'payment_method' => NULL,
                'payment_reference' => NULL,
                'metadata' => NULL,
                'created_at' => '2026-02-13 11:37:34',
                'updated_at' => '2026-02-13 12:41:20',
            ),
            7 => 
            array (
                'id' => 113,
                'survey_id' => 17,
                'user_id' => 10,
                'answers' => '[null, 2, 2, 3, null, 3, ["infraestrutura", "equipamentos"], null, ["Atendimento geral", "Consultas especializadas", "Urgência/emergência"], "2026-02-18", 4, "hbhjbj", 4, "jhbjbjhbj\\n\\nConsidere dividir suas ideias em frases mais curtas.", 4, 4, null, null, null]',
                'feedback' => NULL,
                'status' => 'in_progress',
                'started_at' => '2026-02-15 23:43:31',
                'completed_at' => NULL,
                'completion_time' => 360,
                'time_spent' => NULL,
                'quality_score' => NULL,
                'rating' => NULL,
                'device_type' => 'desktop',
                'browser' => 'Chrome',
                'browser_version' => NULL,
                'os' => NULL,
                'os_version' => NULL,
                'ip_address' => '127.0.0.1',
                'country' => NULL,
                'province' => NULL,
                'city' => NULL,
                'is_paid' => 0,
                'payment_amount' => '80.00',
                'payment_date' => NULL,
                'payment_method' => NULL,
                'payment_reference' => NULL,
                'metadata' => NULL,
                'created_at' => '2026-02-15 23:43:31',
                'updated_at' => '2026-02-15 23:50:48',
            ),
            8 => 
            array (
                'id' => 114,
                'survey_id' => 17,
                'user_id' => 15,
                'answers' => '[null, null, null, null, null, null, null, null, null, null]',
                'feedback' => NULL,
                'status' => 'in_progress',
                'started_at' => '2026-02-16 00:01:47',
                'completed_at' => NULL,
                'completion_time' => 1020,
                'time_spent' => NULL,
                'quality_score' => NULL,
                'rating' => NULL,
                'device_type' => 'desktop',
                'browser' => 'Chrome',
                'browser_version' => NULL,
                'os' => NULL,
                'os_version' => NULL,
                'ip_address' => '127.0.0.1',
                'country' => NULL,
                'province' => NULL,
                'city' => NULL,
                'is_paid' => 0,
                'payment_amount' => '80.00',
                'payment_date' => NULL,
                'payment_method' => NULL,
                'payment_reference' => NULL,
                'metadata' => NULL,
                'created_at' => '2026-02-16 00:01:47',
                'updated_at' => '2026-02-16 00:50:01',
            ),
            9 => 
            array (
                'id' => 115,
                'survey_id' => 15,
                'user_id' => 12,
                'answers' => '[4, ["cloud", "iot"], "resistencia", 3, null, 3]',
                'feedback' => NULL,
                'status' => 'in_progress',
                'started_at' => '2026-02-16 01:00:48',
                'completed_at' => NULL,
                'completion_time' => 900,
                'time_spent' => NULL,
                'quality_score' => NULL,
                'rating' => NULL,
                'device_type' => 'desktop',
                'browser' => 'Chrome',
                'browser_version' => NULL,
                'os' => NULL,
                'os_version' => NULL,
                'ip_address' => '127.0.0.1',
                'country' => NULL,
                'province' => NULL,
                'city' => NULL,
                'is_paid' => 0,
                'payment_amount' => '75.00',
                'payment_date' => NULL,
                'payment_method' => NULL,
                'payment_reference' => NULL,
                'metadata' => NULL,
                'created_at' => '2026-02-16 01:00:48',
                'updated_at' => '2026-02-16 01:58:27',
            ),
        ));
        
        
    }
}