<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UniversitiesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('universities')->delete();
        
        \DB::table('universities')->insert(array (
            0 => 
            array (
                'id' => 1,
            'name' => 'Universidade Eduardo Mondlane (UEM)',
                'acronym' => 'UEM',
                'type' => 'Universidade Pública',
                'location' => 'Maputo',
                'website' => 'https://www.uem.mz',
                'email' => 'info@uem.mz',
                'phone' => '+25821490700',
                'description' => 'Principal universidade pública de Moçambique, fundada em 1962. Referência nacional em ensino superior e pesquisa.',
                'logo_url' => '/storage/logos/universities/uem.png',
                'is_verified' => 1,
                'established_year' => 1962,
                'student_count' => 45000,
                'order' => 1,
                'created_at' => '2026-02-03 17:31:22',
                'updated_at' => '2026-02-03 17:49:06',
            ),
            1 => 
            array (
                'id' => 2,
            'name' => 'Universidade Pedagógica (UP)',
                'acronym' => 'UP',
                'type' => 'Universidade Pública',
                'location' => 'Maputo',
                'website' => 'https://www.up.ac.mz',
                'email' => 'reitoria@up.ac.mz',
                'phone' => '+25821491400',
                'description' => 'Universidade pública especializada em ciências da educação e formação de professores.',
                'logo_url' => '/storage/logos/universities/up.png',
                'is_verified' => 1,
                'established_year' => 1985,
                'student_count' => 28000,
                'order' => 2,
                'created_at' => '2026-02-03 17:31:22',
                'updated_at' => '2026-02-03 17:49:06',
            ),
            2 => 
            array (
                'id' => 3,
            'name' => 'Universidade Lúrio (UniLúrio)',
                'acronym' => 'UniLúrio',
                'type' => 'Universidade Pública',
                'location' => 'Nampula',
                'website' => 'https://www.unilurio.ac.mz',
                'email' => 'geral@unilurio.ac.mz',
                'phone' => '+25827111000',
                'description' => 'Universidade pública do norte de Moçambique, com campus em Nampula, Cabo Delgado e Niassa.',
                'logo_url' => '/storage/logos/universities/unilurio.png',
                'is_verified' => 1,
                'established_year' => 2006,
                'student_count' => 15000,
                'order' => 3,
                'created_at' => '2026-02-03 17:31:22',
                'updated_at' => '2026-02-03 17:49:06',
            ),
            3 => 
            array (
                'id' => 4,
            'name' => 'Universidade Zambeze (UniZambeze)',
                'acronym' => 'UniZambeze',
                'type' => 'Universidade Pública',
                'location' => 'Beira',
                'website' => 'https://www.unizambeze.ac.mz',
                'email' => 'secretaria@unizambeze.ac.mz',
                'phone' => '+25823321000',
                'description' => 'Universidade pública na região centro de Moçambique, com sede na cidade da Beira.',
                'logo_url' => '/storage/logos/universities/unizambeze.png',
                'is_verified' => 1,
                'established_year' => 2006,
                'student_count' => 12000,
                'order' => 4,
                'created_at' => '2026-02-03 17:31:22',
                'updated_at' => '2026-02-03 17:49:06',
            ),
            4 => 
            array (
                'id' => 5,
            'name' => 'Universidade Save (UniSave)',
                'acronym' => 'UniSave',
                'type' => 'Universidade Pública',
                'location' => 'Inhambane',
                'website' => 'https://www.unisave.ac.mz',
                'email' => 'info@unisave.ac.mz',
                'phone' => '+25829320000',
                'description' => 'Universidade pública na província de Inhambane, focada em desenvolvimento regional.',
                'logo_url' => '/storage/logos/universities/unisave.png',
                'is_verified' => 1,
                'established_year' => 2006,
                'student_count' => 8000,
                'order' => 5,
                'created_at' => '2026-02-03 17:31:22',
                'updated_at' => '2026-02-03 17:49:06',
            ),
            5 => 
            array (
                'id' => 6,
            'name' => 'Universidade Rovuma (UniRovuma)',
                'acronym' => 'UniRovuma',
                'type' => 'Universidade Pública',
                'location' => 'Nampula',
                'website' => 'https://www.unirovuma.ac.mz',
                'email' => 'contacto@unirovuma.ac.mz',
                'phone' => '+25827210000',
                'description' => 'Universidade pública nas províncias de Cabo Delgado e Niassa.',
                'logo_url' => '/storage/logos/universities/unirovuma.png',
                'is_verified' => 1,
                'established_year' => 2006,
                'student_count' => 7000,
                'order' => 6,
                'created_at' => '2026-02-03 17:31:22',
                'updated_at' => '2026-02-03 17:49:06',
            ),
            6 => 
            array (
                'id' => 7,
            'name' => 'Universidade Licungo (UniLicungo)',
                'acronym' => 'UniLicungo',
                'type' => 'Universidade Pública',
                'location' => 'Quelimane',
                'website' => 'https://www.unilicungo.ac.mz',
                'email' => 'info@unilicungo.ac.mz',
                'phone' => '+25824220000',
                'description' => 'Universidade pública na província da Zambézia, sede em Quelimane.',
                'logo_url' => '/storage/logos/universities/unilicungo.png',
                'is_verified' => 1,
                'established_year' => 2006,
                'student_count' => 5000,
                'order' => 7,
                'created_at' => '2026-02-03 17:31:22',
                'updated_at' => '2026-02-03 17:49:06',
            ),
            7 => 
            array (
                'id' => 8,
            'name' => 'Instituto Superior de Ciências e Tecnologia de Moçambique (ISCTEM)',
                'acronym' => 'ISCTEM',
                'type' => 'Universidade Privada',
                'location' => 'Maputo',
                'website' => 'https://www.isctem.ac.mz',
                'email' => 'secretaria@isctem.ac.mz',
                'phone' => '+25821490000',
                'description' => 'Instituto superior público especializado em ciências e tecnologia.',
                'logo_url' => '/storage/logos/universities/isctem.png',
                'is_verified' => 1,
                'established_year' => 1996,
                'student_count' => 12000,
                'order' => 8,
                'created_at' => '2026-02-03 17:31:22',
                'updated_at' => '2026-02-03 17:49:06',
            ),
            8 => 
            array (
                'id' => 9,
            'name' => 'Instituto Superior de Transportes e Comunicações (ISUTC)',
                'acronym' => 'ISUTC',
                'type' => 'Universidade Privada',
                'location' => 'Maputo',
                'website' => 'https://www.isutc.ac.mz',
                'email' => 'info@isutc.ac.mz',
                'phone' => '+25821492000',
                'description' => 'Instituto superior público especializado em transportes e comunicações.',
                'logo_url' => '/storage/logos/universities/isutc.png',
                'is_verified' => 1,
                'established_year' => 1997,
                'student_count' => 8000,
                'order' => 9,
                'created_at' => '2026-02-03 17:31:22',
                'updated_at' => '2026-02-03 17:49:06',
            ),
            9 => 
            array (
                'id' => 10,
            'name' => 'Universidade São Tomás de Moçambique (USTM)',
                'acronym' => 'USTM',
                'type' => 'Universidade Privada',
                'location' => 'Maputo',
                'website' => 'https://www.ustm.ac.mz',
                'email' => 'info@ustm.ac.mz',
                'phone' => '+25821430000',
                'description' => 'Universidade privada com enfoque em ciências sociais e humanas.',
                'logo_url' => '/storage/logos/universities/ustm.png',
                'is_verified' => 1,
                'established_year' => 1996,
                'student_count' => 6000,
                'order' => 10,
                'created_at' => '2026-02-03 17:31:22',
                'updated_at' => '2026-02-03 17:49:06',
            ),
            10 => 
            array (
                'id' => 11,
            'name' => 'Universidade Técnica de Moçambique (UDM)',
                'acronym' => 'UDM',
                'type' => 'Universidade Privada',
                'location' => 'Maputo',
                'website' => 'https://www.udm.ac.mz',
                'email' => 'geral@udm.ac.mz',
                'phone' => '+25821435000',
                'description' => 'Universidade privada técnica e tecnológica.',
                'logo_url' => '/storage/logos/universities/udm.png',
                'is_verified' => 1,
                'established_year' => 2001,
                'student_count' => 5000,
                'order' => 11,
                'created_at' => '2026-02-03 17:31:22',
                'updated_at' => '2026-02-03 17:49:06',
            ),
            11 => 
            array (
                'id' => 12,
            'name' => 'Universidade Politécnica (UniPoli)',
                'acronym' => 'UniPoli',
                'type' => 'Universidade Privada',
                'location' => 'Maputo',
                'website' => 'https://www.unipoli.ac.mz',
                'email' => NULL,
                'phone' => NULL,
                'description' => NULL,
                'logo_url' => NULL,
                'is_verified' => 0,
                'established_year' => NULL,
                'student_count' => 0,
                'order' => 12,
                'created_at' => '2026-02-03 17:31:22',
                'updated_at' => '2026-02-03 17:31:22',
            ),
            12 => 
            array (
                'id' => 13,
            'name' => 'Instituto Superior de Ciências de Saúde (ISCISA)',
                'acronym' => 'ISCISA',
                'type' => 'Instituto Superior',
                'location' => 'Maputo',
                'website' => 'https://www.iscisa.ac.mz',
                'email' => NULL,
                'phone' => NULL,
                'description' => NULL,
                'logo_url' => NULL,
                'is_verified' => 0,
                'established_year' => NULL,
                'student_count' => 0,
                'order' => 13,
                'created_at' => '2026-02-03 17:31:22',
                'updated_at' => '2026-02-03 17:31:22',
            ),
            13 => 
            array (
                'id' => 14,
            'name' => 'Instituto Superior de Tecnologias e Gestão (ISTEG)',
                'acronym' => 'ISTEG',
                'type' => 'Instituto Superior',
                'location' => 'Maputo',
                'website' => 'https://www.isteg.ac.mz',
                'email' => NULL,
                'phone' => NULL,
                'description' => NULL,
                'logo_url' => NULL,
                'is_verified' => 0,
                'established_year' => NULL,
                'student_count' => 0,
                'order' => 14,
                'created_at' => '2026-02-03 17:31:22',
                'updated_at' => '2026-02-03 17:31:22',
            ),
            14 => 
            array (
                'id' => 15,
            'name' => 'Instituto Superior Monitor (ISM)',
                'acronym' => 'ISM',
                'type' => 'Instituto Superior',
                'location' => 'Maputo',
                'website' => 'https://www.ism.ac.mz',
                'email' => 'secretaria@ism.ac.mz',
                'phone' => '+25821456000',
                'description' => 'Instituto superior privado com várias unidades.',
                'logo_url' => '/storage/logos/universities/ism.png',
                'is_verified' => 1,
                'established_year' => 1995,
                'student_count' => 4000,
                'order' => 15,
                'created_at' => '2026-02-03 17:31:22',
                'updated_at' => '2026-02-03 17:49:06',
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Outra',
                'acronym' => NULL,
                'type' => 'Outra',
                'location' => NULL,
                'website' => NULL,
                'email' => NULL,
                'phone' => NULL,
                'description' => NULL,
                'logo_url' => NULL,
                'is_verified' => 0,
                'established_year' => NULL,
                'student_count' => 0,
                'order' => 99,
                'created_at' => '2026-02-03 17:31:22',
                'updated_at' => '2026-02-03 17:31:22',
            ),
            16 => 
            array (
                'id' => 17,
            'name' => 'Universidade Púnguè (UniPúnguè)',
                'acronym' => 'UniPúnguè',
                'type' => 'Universidade Pública',
                'location' => 'Manica',
                'website' => 'https://www.unipungue.ac.mz',
                'email' => 'geral@unipungue.ac.mz',
                'phone' => '+25825123000',
                'description' => 'Universidade pública na província de Manica, com campus em Chimoio.',
                'logo_url' => '/storage/logos/universities/unipungue.png',
                'is_verified' => 1,
                'established_year' => 2006,
                'student_count' => 6000,
                'order' => 17,
                'created_at' => '2026-02-03 17:32:32',
                'updated_at' => '2026-02-03 17:49:06',
            ),
            17 => 
            array (
                'id' => 18,
            'name' => 'Instituto Superior Politécnico de Manica (ISPM)',
                'acronym' => 'ISPM',
                'type' => 'Instituto Superior Público',
                'location' => 'Manica',
                'website' => 'https://www.ispm.ac.mz',
                'email' => 'contacto@ispm.ac.mz',
                'phone' => '+25825121000',
                'description' => 'Instituto politécnico público na província de Manica.',
                'logo_url' => '/storage/logos/universities/ispm.png',
                'is_verified' => 1,
                'established_year' => 1999,
                'student_count' => 3000,
                'order' => 18,
                'created_at' => '2026-02-03 17:32:32',
                'updated_at' => '2026-02-03 17:49:06',
            ),
            18 => 
            array (
                'id' => 19,
            'name' => 'Universidade Católica de Moçambique (UCM)',
                'acronym' => 'UCM',
                'type' => 'Universidade Privada',
                'location' => 'Maputo',
                'website' => 'https://www.ucm.ac.mz',
                'email' => 'reitoria@ucm.ac.mz',
                'phone' => '+25824212000',
                'description' => 'Universidade católica privada com várias unidades pelo país.',
                'logo_url' => '/storage/logos/universities/ucm.png',
                'is_verified' => 1,
                'established_year' => 1996,
                'student_count' => 10000,
                'order' => 19,
                'created_at' => '2026-02-03 17:32:32',
                'updated_at' => '2026-02-03 17:49:06',
            ),
        ));
        
        
    }
}