<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('users')->delete();

        \DB::table('users')->insert(array (
            0 =>
            array (
                'id' => 1,
                'name' => 'Administrador do Sistema',
                'email' => 'admin@mozpesquisa.ac.mz',
                'email_verified_at' => '2026-02-03 21:34:58',
                'password' => '$2y$12$HXl1ka3ROiEQpJIzhLM2XuGu5u.pu/U2KuuXLQtC63Pw9zwtoh05u',
                'phone' => '+258840001234',
                'university_id' => NULL,
                'course' => NULL,
                'role' => 'admin',
                'verification_status' => 'approved',
                'verified_at' => '2026-02-03 21:34:58',
                'balance' => '10000.00',
                'email_notifications' => 1,
                'whatsapp_notifications' => 1,
                'profile_info' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-02-03 21:34:58',
                'updated_at' => '2026-02-03 21:34:58',
            ),
            1 =>
            array (
                'id' => 2,
                'name' => 'Carlos Alberto Mondlane',
                'email' => 'carlos.mondlane@uem.ac.mz',
                'email_verified_at' => '2026-02-03 21:34:58',
                'password' => '$2y$12$AySPqZJULDhH/obsaMhO1.cMU2lsOTyHpqVeNHN7yPhzrIJFMWmAy',
                'phone' => '+258841112233',
                'university_id' => 1,
                'course' => 'Engenharia Informática',
                'role' => 'student',
                'verification_status' => 'approved',
                'verified_at' => '2026-02-03 21:34:58',
                'balance' => '850.50',
                'email_notifications' => 1,
                'whatsapp_notifications' => 1,
                'profile_info' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-02-03 21:34:59',
                'updated_at' => '2026-02-06 12:08:25',
            ),
            2 =>
            array (
                'id' => 3,
                'name' => 'Maria Fernanda Silva',
                'email' => 'maria.silva@up.ac.mz',
                'email_verified_at' => '2026-02-03 21:34:58',
                'password' => '$2y$12$B7yBaoRk41qZnmhggu0rVejAJKBGyUcZ1aqJIVHEm3oaMMcWzeCcu',
                'phone' => '+258842223344',
                'university_id' => 2,
                'course' => 'Ciências da Educação',
                'role' => 'student',
                'verification_status' => 'approved',
                'verified_at' => '2026-02-03 21:34:58',
                'balance' => '725.00',
                'email_notifications' => 1,
                'whatsapp_notifications' => 0,
                'profile_info' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-02-03 21:34:59',
                'updated_at' => '2026-02-03 21:34:59',
            ),
            3 =>
            array (
                'id' => 4,
                'name' => 'João Pedro Tembe',
                'email' => 'joao.tembe@unilurio.ac.mz',
                'email_verified_at' => '2026-02-03 21:34:58',
                'password' => '$2y$12$t867uOk2VPtKIHON3Psk9eOFJLQ9kivPuYjVUsaQbFqRhjAJSMS1y',
                'phone' => '+258843334455',
                'university_id' => 3,
                'course' => 'Medicina',
                'role' => 'student',
                'verification_status' => 'approved',
                'verified_at' => '2026-02-03 21:34:58',
                'balance' => '1200.00',
                'email_notifications' => 0,
                'whatsapp_notifications' => 1,
                'profile_info' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-02-03 21:34:59',
                'updated_at' => '2026-02-03 21:34:59',
            ),
            4 =>
            array (
                'id' => 5,
                'name' => 'Ana Paula Macuácua',
                'email' => 'ana.macuacua@isctem.ac.mz',
                'email_verified_at' => NULL,
                'password' => '$2y$12$vS1eqcNyUxqP27tMUohIVeidOo3BtmnJEsOG9URD1GvzKIjf6we3W',
                'phone' => '+258844445566',
                'university_id' => 8,
                'course' => 'Arquitetura',
                'role' => 'student',
                'verification_status' => 'pending',
                'verified_at' => NULL,
                'balance' => '0.00',
                'email_notifications' => 1,
                'whatsapp_notifications' => 1,
                'profile_info' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-02-03 21:34:59',
                'updated_at' => '2026-02-03 21:34:59',
            ),
            5 =>
            array (
                'id' => 6,
                'name' => 'David Jorge Cossa',
                'email' => 'david.cossa@ucm.ac.mz',
                'email_verified_at' => '2026-02-03 21:34:59',
                'password' => '$2y$12$Z8JjPqF3EM/Ns2uhHGZRQeCNKTYYWLlww8GiaCOZiO8GtE.nhkMNG',
                'phone' => '+258845556677',
                'university_id' => 19,
                'course' => 'Direito',
                'role' => 'student',
                'verification_status' => 'approved',
                'verified_at' => '2026-02-03 21:34:59',
                'balance' => '550.25',
                'email_notifications' => 1,
                'whatsapp_notifications' => 1,
                'profile_info' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-02-03 21:34:59',
                'updated_at' => '2026-02-03 21:34:59',
            ),
            6 =>
            array (
                'id' => 7,
                'name' => 'António Fernando Massinga',
                'email' => 'antonio.massinga@gmail.com',
                'email_verified_at' => '2026-02-03 21:34:59',
                'password' => '$2y$12$4jy58kopR6GKOEHTWPUNc.KXwogxZ.vPOUIKWgljEvwHQ09Ocw5iK',
                'phone' => '+258846667788',
                'university_id' => NULL,
                'course' => NULL,
                'role' => 'participant',
                'verification_status' => 'approved',
                'verified_at' => '2026-02-03 21:34:59',
                'balance' => '325.75',
                'email_notifications' => 1,
                'whatsapp_notifications' => 1,
                'profile_info' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-02-03 21:35:01',
                'updated_at' => '2026-02-03 21:35:01',
            ),
            7 =>
            array (
                'id' => 8,
                'name' => 'Célia Regina Nhaca',
                'email' => 'celia.nhaca@hotmail.com',
                'email_verified_at' => '2026-02-03 21:34:59',
                'password' => '$2y$12$uktdYT.l.8IVZ.NxtkJZzunQcEkvDbclfKJSMOzco2i95ahrzhj0y',
                'phone' => '+258847778899',
                'university_id' => NULL,
                'course' => NULL,
                'role' => 'participant',
                'verification_status' => 'approved',
                'verified_at' => '2026-02-03 21:34:59',
                'balance' => '480.50',
                'email_notifications' => 1,
                'whatsapp_notifications' => 0,
                'profile_info' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-02-03 21:35:01',
                'updated_at' => '2026-02-03 21:35:01',
            ),
            8 =>
            array (
                'id' => 9,
                'name' => 'Paulo José Matola',
                'email' => 'paulo.matola@yahoo.com',
                'email_verified_at' => '2026-02-03 21:35:00',
                'password' => '$2y$12$RLm8SsH04YEKmK7pKG4e3.lw9P3vH2eNJTpyU670ZMkKBy/aWY33G',
                'phone' => '+258848889900',
                'university_id' => NULL,
                'course' => NULL,
                'role' => 'participant',
                'verification_status' => 'approved',
                'verified_at' => '2026-02-03 21:35:00',
                'balance' => '145.00',
                'email_notifications' => 0,
                'whatsapp_notifications' => 1,
                'profile_info' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-02-03 21:35:01',
                'updated_at' => '2026-02-07 11:08:05',
            ),
            9 =>
            array (
                'id' => 10,
                'name' => 'Sofia Maria Chaúque',
                'email' => 'sofia.chauque@gmail.com',
                'email_verified_at' => '2026-02-03 21:35:00',
                'password' => '$2y$12$q8MqfZjw5lWkJFvpCFPr4ePyfLNplsQJICrANXveWxj3X2SvjcOC2',
                'phone' => '+258849990011',
                'university_id' => NULL,
                'course' => NULL,
                'role' => 'participant',
                'verification_status' => 'approved',
                'verified_at' => '2026-02-03 21:35:00',
                'balance' => '500.25',
                'email_notifications' => 1,
                'whatsapp_notifications' => 1,
                'profile_info' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-02-03 21:35:01',
                'updated_at' => '2026-02-07 07:51:59',
            ),
            10 =>
            array (
                'id' => 11,
                'name' => 'José Carlos Mucavel',
                'email' => 'jose.mucavel@outlook.com',
                'email_verified_at' => '2026-02-03 21:35:00',
                'password' => '$2y$12$V4JDtr5tGAWlskE5bOy1suCQcE6.Zhaq4In2mYHD0lp7//xSI.kI6',
                'phone' => '+258840011122',
                'university_id' => NULL,
                'course' => NULL,
                'role' => 'participant',
                'verification_status' => 'approved',
                'verified_at' => '2026-02-03 21:35:00',
                'balance' => '275.50',
                'email_notifications' => 1,
                'whatsapp_notifications' => 1,
                'profile_info' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-02-03 21:35:01',
                'updated_at' => '2026-02-03 21:35:01',
            ),
            11 =>
            array (
                'id' => 12,
                'name' => 'Teresa Alberto Nhantumbo',
                'email' => 'teresa.nhantumbo@gmail.com',
                'email_verified_at' => '2026-02-03 21:35:00',
                'password' => '$2y$12$nHJ.rbvyNeWZG1UWwkSLfesf3cKdP9bqPSq3RrLBXjeGQ.Pls3sWu',
                'phone' => '+258841122233',
                'university_id' => NULL,
                'course' => NULL,
                'role' => 'participant',
                'verification_status' => 'approved',
                'verified_at' => '2026-02-03 21:35:00',
                'balance' => '150.00',
                'email_notifications' => 0,
                'whatsapp_notifications' => 0,
                'profile_info' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-02-03 21:35:01',
                'updated_at' => '2026-02-03 21:35:01',
            ),
            12 =>
            array (
                'id' => 13,
                'name' => 'Rogério Francisco Sitoe',
                'email' => 'rogerio.sitoe@hotmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$k9/XIAn3QxVDPmzpOmgKI.onSpcm7fPn8nyQ5OR51ovzBtlR9gdqG',
                'phone' => '+258842233344',
                'university_id' => NULL,
                'course' => NULL,
                'role' => 'participant',
                'verification_status' => 'pending',
                'verified_at' => NULL,
                'balance' => '0.00',
                'email_notifications' => 1,
                'whatsapp_notifications' => 1,
                'profile_info' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-02-03 21:35:01',
                'updated_at' => '2026-02-03 21:35:01',
            ),
            13 =>
            array (
                'id' => 14,
                'name' => 'Luísa Domingos Muianga',
                'email' => 'luisa.muianga@yahoo.com',
                'email_verified_at' => '2026-02-03 21:35:01',
                'password' => '$2y$12$nv3/h2j3o3YZ7Y6tNJrdbuSPwdA6i168u8vNWgMrLV1lpgM5.S3vK',
                'phone' => '+258843344455',
                'university_id' => NULL,
                'course' => NULL,
                'role' => 'participant',
                'verification_status' => 'approved',
                'verified_at' => '2026-02-03 21:35:01',
                'balance' => '385.75',
                'email_notifications' => 1,
                'whatsapp_notifications' => 1,
                'profile_info' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-02-03 21:35:01',
                'updated_at' => '2026-02-03 21:35:01',
            ),
            14 =>
            array (
                'id' => 15,
                'name' => 'Fernando João Saíde',
                'email' => 'fernando.saide@gmail.com',
                'email_verified_at' => '2026-02-03 21:35:01',
                'password' => '$2y$12$IZ0Uz2enH9xMlbJzQdKqVuor0fdokjcgIXgm0X.WlaVfRyn1hNXpu',
                'phone' => '+258844455566',
                'university_id' => NULL,
                'course' => NULL,
                'role' => 'participant',
                'verification_status' => 'approved',
                'verified_at' => '2026-02-03 21:35:01',
                'balance' => '330.00',
                'email_notifications' => 0,
                'whatsapp_notifications' => 1,
                'profile_info' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-02-03 21:35:01',
                'updated_at' => '2026-02-13 09:54:16',
            ),
            15 =>
            array (
                'id' => 16,
                'name' => 'Marta José Amisse',
                'email' => 'marta.amisse@outlook.com',
                'email_verified_at' => NULL,
                'password' => '$2y$12$5FSWaWkKfgC7aOBGoaBCo./u.kI58n3zC9IYPhJNlDX/hHTOAmNAC',
                'phone' => '+258845566677',
                'university_id' => NULL,
                'course' => NULL,
                'role' => 'participant',
                'verification_status' => 'approved',
                'verified_at' => NULL,
                'balance' => '0.00',
                'email_notifications' => 1,
                'whatsapp_notifications' => 0,
                'profile_info' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-02-03 21:35:01',
                'updated_at' => '2026-02-12 12:37:02',
            ),
        ));


    }
}
